### ISSUE TITLE
Improve debug info

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-test-tools-resources#156]
## What protocol and version of the protocol are you testing?

CTAP2

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.412

## Issue description
On a fail, the tools is not printing the command sent to the authenticator, neither the response from it. Therefore, it's quite hard to debug and reproduce the fail.

**Comment by herrjemand** [comment]
Good idea @eugenIFX!

**Comment by herrjemand** [comment]
cc @jovasco

**Comment by jovasco** [comment]
Thanks, @herrjemand.

The old tools (the BLE one anyway) had a "trace" option that just dumps everything that is sent and received, regardless of whether the tests failed or succeeded.

**Comment by eugenIFX** [comment]
Hi @herrjemand , @jovasco ,

It will be great to have this option again inside the tool. Because the tool is not finishing the execution after the first fail, I think it will be a big plus to have a message saying, for example, "Test X, sent: Y, expected: CTAP1_ERR_SUCCESS, received: Z" (either the trace option is enabled or not).

**Comment by jovasco** [comment]
@eugenIFX I agree. I have added a separate issue for the full tracing: #157

**Comment by eugenIFX** [comment]
Thanks, @jovasco .

**Comment by herrjemand** [comment]
@eugenIFX I think having "Test X, sent: Y, expected: CTAP1_ERR_SUCCESS, received: Z" would make error messages really hard to read, because " sent Y would look like sent: YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY. Instead I've added trace dump in the console. Does it solves your problem, or do you think that there is additional feature needs to be added?

**Comment by jovasco** [comment]
Can't they be made multiline?

**Comment by herrjemand** [comment]
@jovasco yeah... The way that mocha presents that stuff is not multiline. I can add it when I am done with the new UI.

**Comment by eugenIFX** [comment]
@herrjemand the idea was to make the debug easier and be able to isolate and reproduce the fail (btw, my request is just for the failing tests). I think it will be hard if I will have to read the full trace info and find the test which is failing. Therefore, it will be great to have multiline info. 
As an user, it's not important to see in the fail message any javascript exception.

**Comment by herrjemand** [comment]
@eugenIFX Yeah, I hear that. For now you can see send/received buffers in console. I will work in future versions to make it look better
