### ISSUE TITLE
txAuthSimple transaction confirmation tests do not accept inserted newlines

### ISSUE THREAD

**Issue by jovasco** [fido-alliance/conformance-test-tools-resources#469]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?

Unknown

## Issue description

the txAuthSimple extension tests do not accept inserted newlines, which is explicitly allowed by the WebAuthn spec. The spec allows the authenticator to insert newlines and then says to include these newlines in the returned string.

**Comment by FabianHenneke** [comment]
I am also hitting this issue with my authenticator. Do you know whether this has a chance of becoming unblocked in the near future?

For my own tests, I wrote the following verification routine that allows adding newlines. I hereby release it under CC0 for anyone to build on freely:

```es6
function verify(originalPrompt, actualPrompt) { 
  let i = 0;  
  for (let j = 0; j < actualPrompt.length; j++) {
    // If i has reached the end of originalPrompt, then 
    // originalPrompt[i] is undefined and the following
    // condition is never satisfied.
    if (originalPrompt[i] == actualPrompt[j])
      i++;
    else if (actualPrompt[j] != '\n')
      return false;    
  }  
  // Ensure that originalPrompt appears as a subsequence
  // of actualPrompt.
  if (i != originalPrompt.length)    
    return false;
  
  return true;
}
```
