### ISSUE TITLE
Metadata service tests JWT x5c certificate specifies CRL distribution point returning HTTP 404

### ISSUE THREAD

**Issue by bdewater** [fido-alliance/conformance-test-tools-resources#476]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
1.1.2

## What is the OS and the version are you running?
macOS 10.14 Mojave

## Issue description

One of the endpoints generated by the conformance MDS has a certificate inside the JWT x5c header that has a CRL distribution point extension whose URL responds with 404: https://fidoalliance.co.nz/safetynetpki/crl/FIDO%20Fake%20Root%20Certificate%20Authority%202018.crl

[Here's the certificate in question](https://lapo.it/asn1js/#MIIFDTCCA_WgAwIBAgIPBNfPVzSNvbKOG0eGBuEJMA0GCSqGSIb3DQEBCwUAMFAxCzAJBgNVBAYTAlVTMRYwFAYDVQQKDA1GSURPIEFsbGlhbmNlMSkwJwYDVQQDDCBGSURPIEFsbGlhbmNlcyBGQUtFIFJvb3QgQ0EgLSBTMTAeFw0xNzAyMDEwMDAwMDBaFw0zNTAxMzEyMzU5NTlaMG4xCzAJBgNVBAYTAlVTMSswKQYDVQQKDCJGSURPIEFsbGlhbmNlcyBGQUtFIFRydXN0IFNlcnZpY2VzMTIwMAYDVQQDDClGSURPIEFsbGlhbmNlcyBGQUtFIEludGVybmV0IEF1dGhvcml0eSBGMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMEHmFfbNypPuq94k-SSCiUvXSumolYpHYHikPaV2jQbbXvGuJ-w8yxzHGURFZQLfCFVrTZ269ebvY2pNlhUSpNJc7SpholSr9tCjuHdGL3uvBdpxaZjvtdVE6yn5ZvCxyx_hAguEdkdPuVEmdVDr64c68d28oi_3YsFnIbqMnuXv8pqvFasGjdTWFC3auJGdu2v65sBU4vWcrEFdYj0MgwOD0loYHb-0zKK9wxfiZPUV8HEZbKwDWf5jouacJeWZ324WF1LHOjWrxHgoDQBizs2qUFJvCNinsaCSM5JSxQulMGdbDUUSvY3nikznryNrN6f_ORnfk2-KIztct2kOIcCAwEAAaOCAcQwggHAMAsGA1UdDwQEAwIBhjBLBgNVHSAERDBCMEAGBmeBDAECAjA2MDQGCCsGAQUFBwIBFihodHRwczovL2ZpZG9hbGxpYW5jZS5jby5uei9zYWZldHluZXRwa2kvMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjASBgNVHRMBAf8ECDAGAQH_AgEAMB0GA1UdDgQWBBSj2hfgiDTbyaZcAJBLWywgFAP1BzAfBgNVHSMEGDAWgBSqNv9BadKdijvYHGXTW95rcC2UkDB0BgNVHR8EbTBrMGmgZ6BlhmNodHRwczovL2ZpZG9hbGxpYW5jZS5jby5uei9zYWZldHluZXRwa2kvY3JsL0ZJRE8lMjBGYWtlJTIwUm9vdCUyMENlcnRpZmljYXRlJTIwQXV0aG9yaXR5JTIwMjAxOC5jcmwwewYIKwYBBQUHAQEEbzBtMGsGCCsGAQUFBzABhl9odHRwczovL2ZpZG9hbGxpYW5jZS5jby5uei9zYWZldHluZXRwa2kvRklETyUyMEZha2UlMjBSb290JTIwQ2VydGlmaWNhdGUlMjBBdXRob3JpdHklMjAyMDE4LmNydDANBgkqhkiG9w0BAQsFAAOCAQEAiOOH0YA-q_YGCY79kfKU_ZQjbK0MsRwCzZG9S_m4iwIczQ3GakOFH7ry4yFqQ58cO-9gbVrsBhH54BI0MwS5iCXjhv1bgk1Hltw8KHRoslJryDQPzR3S2EMvx-lzx2Xv6s2XxvHRRC8KQYT_OWdfi9CfB9dQoKcdm5l1fD9gVV6mxezkrQl7C0Kfe4Zpy147HOoZ04rOxlxtt3WHsFgWL_Mn0dbbAS0xxCNdw88IiLN7GzKzRrbw6cHsBDavxlXFcJu8VqSjNMRFDH1P4AGbSeX8yuD1gs7wvlrAydoLvq67PP24wU4B1uQYnYEmC5oAvs6qSvlptDbNs7chMy0apw)

Not sure if it's related but it sounds like this issue with Android Key attestation: https://github.com/fido-alliance/conformance-tools-issues/issues/468

**Comment by bdewater** [comment]
FWIW I'm working around it by having my HTTP client ignore a failed download - OpenSSL is smart enough when set with the correct [verification flags](https://www.openssl.org/docs/manmaster/man3/X509_VERIFY_PARAM_set_depth.html#VERIFICATION-FLAGS) (`OpenSSL::X509::V_FLAG_CRL_CHECK | OpenSSL::X509::V_FLAG_CRL_CHECK_ALL` in Ruby) to raise an error if a CRL is missing.

**Comment by sbweeden** [comment]
FWIW2: I worked around it (temporarily) a different way as I am using Java PKIX trust path validator.

By adding a local hosts file entry pointing fidoalliance.co.nz off to an IP that has nothing listening on port 443 and using the PKIX SOFT_FAIL option (see https://docs.oracle.com/javase/8/docs/api/java/security/cert/PKIXRevocationChecker.Option.html#SOFT_FAIL) then trust path validation won't fail because the CRL host cannot be reached. It turns out that if the host is reachable on the port (443) and returns a 404, then it does still fail.

**Comment by kishorechandran41** [comment]
@herrjemand help us by resolving this, only this test case is failing for me. The issue seems to exist for quite some time.

**Comment by kishorechandran41** [comment]
The metadata for this case (Virtual RSA PKCS 1.5 SHA256 FIDO2 Conformance Testing CTAP2 Authenticator with SafetyNet attestation.json) contains 4 certificates of which 2 have broken URI for verification, containing space in the URI. Also the same do not chain to the trusted root certificates. Please share us the updated patch for the same. On disabling the signature verification we are able to pass the attestation, which ideally will only be a temporary fix. Is it possible to fix it permanently.
