### ISSUE TITLE
Show server response for successful test cases

### ISSUE THREAD

**Issue by bdewater** [fido-alliance/conformance-test-tools-resources#477]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
v1.1.4

## What is the OS and the version are you running?
macOS 10.14 Mojave

## Issue description
Right now it's hard to see if test cases that are expected to fail are failing for the right reason. I've run into a couple of instances already where the an expected failure test case succeeded for the wrong reason. A typical example is a parsing error being returned instead of the expected verification error.

I feel it would be extremely useful to be able to toggle test cases and always be able to see the server response, instead of only on unexpected test failures like is the case now.

**Comment by aseigler** [comment]
100% agree. As is, I have to open the inspector and verify one by one that each negative test is failing for the right reason. It takes much longer than it really should.

**Comment by herrjemand** [comment]
Would be great enhancement. But requires to redesign entire UI.

**Comment by bdewater** [comment]
I'm not sure I follow why it needs an entire redesign.

As it stands right now, a successful failure shows the test name and the collapsed test code which can be shown by clicking on it. I suspect these code snippets are not useful for most users of the tools. If that code instead can show server response as it is already being logged in the inspector console, the problem would be solved 🙂

**Comment by herrjemand** [comment]
The current UI is generated by the Mocha, and so I need to write full new UI in order so solve that issue

**Comment by herrjemand** [comment]
It is now logging req/resp in the console. So closing it
