### ISSUE TITLE
FIDO2 Options Resident-Key P-3: authenticatorGetAssertion without UV expected to return user info

### ISSUE THREAD

**Issue by FabianHenneke** [fido-alliance/conformance-test-tools-resources#528]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?

1.3.0

## What is the OS and the version are you running?

Windows 10

## Issue description

In the FIDO2 Options Resident-Key P-3 test, if the authenticator supports UV but not client PIN, the assertion request sent to the authenticator will not be marked as requiring UV even though the response is expected to contain user info. 

It seems that in the `else` branch of `sendGetAssertionWithPinOrNot`, `generateGetAssertionReqCBOR` should be called with a non-empty `options` parameter with `options.uv=true`.

**Comment by herrjemand** [comment]
@FabianHenneke UV is either an actual UV or ClientPin.

**Comment by FabianHenneke** [comment]
> @FabianHenneke UV is either an actual UV or ClientPin.

I understand that there is some confusion between UV taken to mean either "user verification internal to the authenticator" or "any method of user verification, including client PIN". However, I have not yet understood how this relates to the reported issue. I would appreciate it if you could elaborate on this a bit more as I may very well have misunderstood the spec.

Based on my understanding of (and experiments with) the test case, it sends a PIN with the GetAssertion requests if the authenticator supports client PIN, which will lead the authenticator to return user PII since some method of UV (external to the authenticator in this case) was performed. This part of the test appears to behave correctly.

But the test case will not request any kind of UV for the GetAssertion request if the authenticator does not support clientPin (but does support internal UV, as otherwise the test case would have been skipped). Since the GetAssertion request is sent without `uv=true` in its options, the authenticator should not return any user PII, but the test case then proceeds to check that such info is indeed returned. It seems to me that compliant authenticators with displays and internal UV are therefore unable to pass this test.

**Comment by gddcgmsrd41ud** [comment]
Hello @herrjemand , we are facing the exact same issue described here by @FabianHenneke  (with the current test tool 1.3.4 on MacOS)
Could you please fix this bug and not just close the issue without comment?!

**Comment by gddcgmsrd41ud** [comment]
Here is also a log:
[fido2_resident_key_P-3.log](https://github.com/fido-alliance/conformance-test-tools-resources/files/5090666/fido2_resident_key_P-3.log)

**Comment by herrjemand** [comment]
@FabianHenneke yes, this is correct.

UV flag in getInfo states that some **on device** UV method available. Example: Fingerprint, Face, Iris, Pincode(via keyboard on the device), so internal UV.

The request with UV set to 1, means that Client requires that Authenticator to force INTERNAL UV.

ClientPin is an EXTERNAL UV method. So that means it is not specified in GetInfo as UV and not enforced via UV flag in request. But it is still a UV, which means that it will set in response UV flag to 1.

![Screenshot 2020-10-02 at 16 02 19](https://user-images.githubusercontent.com/1636116/94925960-b7e2da80-04c8-11eb-9899-399e1ec4d6fc.png)

Referring to the specs https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#using-pinToken-in-authenticatorMakeCredential


Does this answer you question @gddcgmsrd41ud @FabianHenneke?

**Comment by Weltpilot** [comment]
@herrjemand There seems to be a misunderstanding. Our authenticator does not support clientPIN, but internal user verification. But in this testcase the option "uv=True" is missing from the getAssertion command -> user verification is not done -> the returned user info only contains the ID, not the name of the user.

§5.2 of CTAP2.0 states: "PublicKeyCredentialUserEntity structure containing the user account information. User identifiable information (name, DisplayName, icon) MUST not be returned if user verification is not done by the authenticator. "

**Comment by gddcgmsrd41ud** [comment]
@herrjemand There seems to be a misunderstanding. Our authenticator does not support clientPIN but internal user verification (by fingerprint match). But this testcase does not request user verification in the getAssertion command (see logfile) -> user verification is not done -> the response only contains the user ID

§5.2 of CTAP2.0 states:
"PublicKeyCredentialUserEntity structure containing the user account information. User identifiable information (name, DisplayName, icon) MUST not be returned if user verification is not done by the authenticator. "

For the testcase to work, the option uv=True" has to be set (as already suggested in the original description of this issue).

**Comment by herrjemand** [comment]
Ok, lemme check

**Comment by FabianHenneke** [comment]
@herrjemand Let me briefly describe what I believe to cause the misunderstanding here:

In the **input** to the `authenticatorGetAssertion` command, `pinAuth` (which is also called `pinUvAuthToken` in CTAP 2.1) being present means "perform external user verification", whereas `uv` set to `true` means "perform internal user verification". 

In the **output** of the `authenticatorGetAssertion` command, the `uv` flag is set if at least one of internal or external user verification has been performed (but it doesn't matter which one).

As @gddcgmsrd41ud has cited:
> §5.2 of CTAP2.0 states:
> "PublicKeyCredentialUserEntity structure containing the user account information. User identifiable information (name, DisplayName, icon) MUST not be returned if user verification is not done by the authenticator. "

This means that private information must only be returned if internal or external user verification has been performed (that is, if the **output** of the `authenticatorGetAssertion` command would have the `uv` flag set).

In the test case we are currently discussing, external user verification is correctly requested if supported by the authenticator, meaning that private information is allowed to be returned. 
However, and this is now the issue @gddcgmsrd41ud and I are reporting, if the authenticator supports only internal user verification, than no form of user verification is ever requested by the conformance tools. This leaves the authenticator no other choice than to **not** return any private information, which in turn leads to a failed test.

**Comment by herrjemand** [comment]
new build! https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.5.0/
