### ISSUE TITLE
FIDO2 Extensions txAuthSimple: preconditions check for txAuthGeneric

### ISSUE THREAD

**Issue by FabianHenneke** [fido-alliance/conformance-test-tools-resources#535]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?

1.3.2

## What is the OS and the version are you running?

Windows 10

## Issue description

The txAuthSimple test suite is skipped unless the authenticator supports the txAuthGeneric extension, which is a different one. The precondition should check whether "txAuthSimple" is in the list of extensions returned in the GetInfo response, not whether "txAuthGeneric" is in it.

**Comment by herrjemand** [comment]
@FabianHenneke Thanks. Will be fixed in the next build
