### ISSUE TITLE
iOS BLE authenticator unable to set 'Firmware Revision' characteristic.

### ISSUE THREAD

**Issue by saravnandm** [fido-alliance/conformance-test-tools-resources#541]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

ASM+Authr

## What is the version of the tool are you using?
1.2.1

## What is the OS and the version are you running?
macOS Mojave 10.14.6

## Issue description
I'm trying to implement a Fido2 iOS BLE authenticator.

As per the CTAP2 specification https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#ble-device-information-service
the authenticator SHALL implement the Device Information Service with 
Manufacturer Name String, Model Number String, and Firmware Revision String characteristics.

The problem is, in iOS Device Information Service and its characteristics are system-wide and cannot be set by individual apps. 
I cannot even make iOS to provide the Firmware Revision String characteristic,
and that results in a conformance testing tool failing.

This prevents my iOS+BLE based authenticator from being certified. Any solution to solve this problem?

**Comment by herrjemand** [comment]
@saravnandm So far we had four successful FIDO2 iOS authrs certified, but I will do some research

**Comment by saravnandm** [comment]
Yes, I have noticed that some people get certified for iOS fido2 BLE . Please let me know. Also, the conformance tool for the authenticator is not consistent. Every time getting different behavior

**Comment by herrjemand** [comment]
@saravnandm Any examples of that?

**Comment by saravnandm** [comment]
So far I have noticed the following inconsistency.

1. Sometimes getting timeout for the first test cases in every section of 'makeCredential' & 'getAssertion'.
2. Based on the order I have selected in 'SELECT TESTS TO RUN', under 'CTAP2 Tests'. Seeing different results.
3. The request of **Authr-MakeCred-Req-6 Test options in MakeCredential request** always failed to parse (CBOR). Then how can the authenticator come to know its an  'option error / invalid option' to send the error code?

**Comment by herrjemand** [comment]
@saravnandm Try latest build. I have changed some of the logic.

**Comment by saravnandm** [comment]
@herrjemand thanks for the update. Let me check and post you.

**Comment by saravnandm** [comment]
Hi,
Seems like the first timeout (1st) is solved. But still, 2,3 & iOS 'Firmware Revision' characteristics are not solved.

**Comment by saravnandm** [comment]
Please check the following 

BLE-1 Test CTAP2 BLE support
P-1 Check that authenticator implements Device Information Service(0x180A), and check that: (a) It contains "Manufacturer Name String" characteristic(0x2A29). (b) It contains "Model Number String" characteristic(0x2A24). (c) It contains "Firmware Revision String" characteristic(0x2A26). ‣
AssertionError: "Device Information" missing "Firmware Revision String" characteristic(0x2A26)!: expected undefined to not equal undefined
    at r.it (eval at compileCode (js/sandbox.js:25:26), <anonymous>:3312:16)
    at e (js/vendor/mocha.min.js:1:39758)
    at s.run (js/vendor/mocha.min.js:1:39694)
    at h.runTest (js/vendor/mocha.min.js:1:45264)
    at file:///Applications/fido-conformance-tools-electron%201.3.4.app/Contents/Resources/app/app/js/vendor/mocha.min.js:1:46126
    at r (js/vendor/mocha.min.js:1:44576)
    at file:///Applications/fido-conformance-tools-electron%201.3.4.app/Contents/Resources/app/app/js/vendor/mocha.min.js:1:44645
    at r (js/vendor/mocha.min.js:1:44051)
    at file:///Applications/fido-conformance-tools-electron%201.3.4.app/Contents/Resources/app/app/js/vendor/mocha.min.js:1:44463
    at c (js/vendor/mocha.min.js:1:1064)
    
let services = navigator.fido.fido2.ble.getAllServices(getDeviceInfo());
assert.isDefined(services['180a'], 'Authenticator MUST implement "Device Information" service!');
assert.isDefined(services['180a'].characteristics['2a29'], '"Device Information" missing "Manufacturer Name String" characteristic(0x2A29)!');
assert.isDefined(services['180a'].characteristics['2a24'], '"Device Information" missing "Model Number String" characteristic(0x2A24)!');
assert.isDefined(services['180a'].characteristics['2a26'], '"Device Information" missing "Firmware Revision String" characteristic(0x2A26)!');

P-2 Check that authenticator implements Generic Access Profile Service(0x1800), and check that: (a) It contains "Device Name" characteristic(Ox2A00). (b) It contains "Appearance" characteristic(0x2A01). [SKIPPED DUE TO NOBLE OSX ISSUES] 
P-3 Check that FIDO service is a primary service. [SKIPPED DUE TO NOBLE ISSUES]

**Comment by herrjemand** [comment]
@saravnandm Sorry, we are still investigating those issues.

**Comment by saravnandm** [comment]
@herrjemand thank you. These issues stopping us to proceed with the certification. Hope will get a new version with bug fixes soon.

**Comment by saravnandm** [comment]
@herrjemand any update?

**Comment by Cristianopalazzi** [comment]
Hi @saravnandm, I have the same problem with the Firmware Revision String characteristic. Have you found a solution?

**Comment by saravnandm** [comment]
Still no solution.

**Comment by eehgnak** [comment]
Hello @saravnandm 
I also have a "Firmware Revision String" problem.
Still haven't found a solution?

**Comment by saravanandm** [comment]
@eehgnak last tested 6 months back. No solution. It's a conformance tool issue, no need to worry about this issue.

**Comment by eehgnak** [comment]
@saravanandm Did you have any problems when getting FIDO2 authenticator certification?

**Comment by eehgnak** [comment]
@saravanandm When certifying FIDO2 authenticators, wasn't this a problem?

**Comment by saravanandm** [comment]
@eehgnak had the same doubt. I sent an email to the fido team and get it confirmed. It shouldn't be a problem to get certified as it is a issue in the conformance tool. Recommend you send an email to the fido team. Are you using Chrome to test iOS authenticator?

**Comment by eehgnak** [comment]
@saravanandm We are currently testing with the conformance tool, and will be working with Chrome. 
Thank you for answer.

**Comment by herrjemand** [comment]
We had finally achieved a progress and restrictions on the DeviceInfo have been laxed.

Please try this build

https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/v1.6.17/
