### ISSUE TITLE
TypeError: Cannot read property '2' of undefined

### ISSUE THREAD

**Issue by saravnandm** [fido-alliance/conformance-test-tools-resources#549]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.2

## What is your implementation class?

ASM+Authr

## What is the version of the tool are you using?
1.3.4

## What is the OS and the version are you running?
iOS

## Issue description
I'm always getting this error for makeCredential. Any idea? I tried rebuilding but no luck.

F-7 Send CTAP2 authenticatorMakeCredential(0x01) message, with "excludeList" that contains "PublicKeyCredentialDescriptor" with "id" set to the ID of the previously registered authenticator, wait for the response, and check that Authenticator returns an error CTAP2_ERR_CREDENTIAL_EXCLUDED(0x19). ‣
**TypeError: Cannot read property '2' of undefined**
    at sendCTAP_CBOR.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:4229:108)
    at <anonymous>let makeCredStruct = generateGoodCTAP2MakeCreditentials();
let commandBuffer = generateMakeCreditentialsReqCBOR(makeCredStruct.clientDataHash, makeCredStruct.rp, makeCredStruct.user, makeCredStruct.pubKeyCredParams)
let rp = makeCredStruct.rp;
return sendCTAP_CBOR(commandBuffer)
    .then((ctap2Response) => {
        assert.strictEqual(ctap2Response.statusCode, CTAP_ERROR_CODES.CTAP1_ERR_SUCCESS, `Expected authenticator to succeed with CTAP1_ERR_SUCCESS(${hexifyInt(CTAP_ERROR_CODES.CTAP1_ERR_SUCCESS)}). Got ${CTAP_ERROR_CODES[ctap2Response.statusCode]}(${hexifyInt(ctap2Response.statusCode)})`);
        let authDataStruct = parseAuthData(ctap2Response.cborResponseStruct[MakeCredentialsRespKeys.authData]);
        let makeCredStruct = generateGoodCTAP2MakeCreditentials();
        makeCredStruct.excludeList = [
            {type: 'public-key', id: authDataStruct.credId}
        ];
        let commandBuffer = generateMakeCreditentialsReqCBOR(makeCredStruct.clientDataHash, rp, makeCredStruct.user, makeCredStruct.pubKeyCredParams, makeCredStruct.excludeList)
        return sendCTAP_CBOR(commandBuffer)
            .then((ctap2Response) => {
                assert.strictEqual(ctap2Response.statusCode, CTAP_ERROR_CODES.CTAP2_ERR_CREDENTIAL_EXCLUDED, `Expected authenticator to fail with CTAP2_ERR_CREDENTIAL_EXCLUDED(${CTAP_ERROR_CODES.CTAP2_ERR_CREDENTIAL_EXCLUDED}). Got ${CTAP_ERROR_CODES[ctap2Response.statusCode]}(${ctap2Response.statusCode})`);
            })
    })

**Comment by herrjemand** [comment]
Should be fixed now
