### ISSUE TITLE
Customize test timeout 

### ISSUE THREAD

**Issue by Cristianopalazzi** [fido-alliance/conformance-test-tools-resources#551]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

U2F/FIDO2

## What is your implementation class?

ASM+Authr

## What is the version of the tool are you using?
1.3.4

## What is the OS and the version are you running?
MacOs Mojave 10.14.3

## Issue description
I'm implementing a iOS/Android BLE authenticator using a specific technology that needs several seconds to complete a makeCredential or getAssertion request. I tested my implementation on test websites like "webauthn.io", "webauthn.org" or "webauthn.bin.coffee" and it works properly by sending keep alive messages. Instead, the same implementation doesn't work with the conformance tool because of the timeout that occurs after about 5 seconds, even if I send the keep alive messages. Is there a way to change the timeout value ?

**Comment by herrjemand** [comment]
@Cristianopalazzi That should be fixed now with new BLE stack
