### ISSUE TITLE
About official test execution

### ISSUE THREAD

**Issue by apthilaga** [fido-alliance/conformance-test-tools-resources#554]
## What protocol and version of the protocol are you testing?
FIDO2 v2.1

## What is your implementation class?
Authr

## What is the version of the tool are you using?
fido-conformance-tools-electron-win32-x64-1.3.4-installer

## What is the OS and the version are you running?
Windows 10 64 bit

## Issue description
URL - https://fidoalliance.org/certification/functional-certification/conformance/ 
mentions 
"When an implementation is ready for the official test, simply select that the test being run is an official test and the results will be logged as part of the official records."

w.r.t to above statement, I have the following queries.
1. Where does this official test performed?
2. If its performed by vendor, Please tell what is the settings to be done in the test tool. I am unable to find settings for official test. (for the sentence "simply select that the test being run is an official test")
3. Where can I find the test report & logs per test?

**Comment by gddcgmsrd41ud** [comment]
Normally, if you run all conformance tests successfully, you will see a button to submit your results. This is a prerequisite before taking part in the interop tests with your implementation.

**Comment by herrjemand** [comment]
@apthilaga First you pass the conformance tools. Submit results.

Then you register for the interoperability event. Generally it happening somewhere around the globe, but since it's COVID, it happens online this year.

You can read more here https://fidoalliance.org/certification/functional-certification/
