### ISSUE TITLE
CTAP2: Tests for PIN policy occasionally fail

### ISSUE THREAD

**Issue by gddcgmsrd41ud** [fido-alliance/conformance-test-tools-resources#556]
## What protocol and version of the protocol are you testing?

FIDO2, CTAP2

## What is your implementation class?

NFC Authenticator without display

## What is the version of the tool are you using?

v1.3.4

## What is the OS and the version are you running?

MacOS Catalina

## Issue description

Tests don't use correct padding/formatting. They only make sure that the last byte(s) of the PIN buffer are padded with zero, but use random bytes for the rest. For a PIN of length n, the tests must set the first n bytes to a value other than zero.

**Comment by herrjemand** [comment]
@gddcgmsrd41ud That should not be an issue, considering that you are always working with 64byte block

**Comment by gddcgmsrd41ud** [comment]
@herrjemand 
"Platform checks the byte length of newPin against the max UTF-8 representation limit of 63 bytes and returns CTAP2_ERR_PIN_POLICY_VIOLATION if the check fails."
"During encryption, newPin is padded with trailing 0x00 bytes and is of minimum 64 bytes length. "
Therefore, if you want to test a PIN of length 64 bytes, the test has to make sure that all 64 bytes are not zero. Don't you agree?
