### ISSUE TITLE
Wrong APDUs in U2F test cases

### ISSUE THREAD

**Issue by tsenger** [fido-alliance/conformance-test-tools-resources#557]
## What protocol and version of the protocol are you testing?

U2F v1.1

## What is your implementation class?

Authr

## What is the version of the tool are you using?

FIDO Conformance Tools v1.3.4(U2F 1.1)

## What is the OS and the version are you running?
Windows 10 64bit Rev 1909

## Issue description
I currently test a Fido U2F implementation a Javacard connected via NFC.
There are some U2F Authenticator test cases which seem to be wrong because they require that the card answers with a SW that doesn't match when sending the APDU defined in the test case.
Issues #544 also mentioned it.
For example:

1. "Send Register command with invalid INS, wrapped in Short APDU, and check that authenticator returns APDU error SW_INS_NOT_SUPPORTED(0x6D00)" will send the following APDU to the Authenticator:  0x80, 0x75, 0x00, 0x00, <LC>, <RegisterData>.
Expected Result is SW_INS_NOT_SUPPORTED(0x6D00).  But the authenticator answer with SW_CLA_NOT_SUPPORTED(0x6E00) because CLA 0x80 is not the expected CLA 0x00.

2.  Same with "F-2 Send Register command with invalid INS, wrapped in Extended APDU, and check that authenticator returns APDU error SW_INS_NOT_SUPPORTED(0x6D00)"

3. "Send Register command wrapped in Short APDU with invalid Lc, and check that authenticator returns APDU error SW_WRONG_LENGTH(0x6700)" will send the following APDU:  0x80, 0x10, 0x00, 0x00, 0xFF, <RegisterData>. This APDU contains three errors in sum: CLA 0x80 is wrong (should be 0x00), INS 0x10 is wrong (should be 0x01), LC is wrong (which is intended). So an authenticator could be react to any of these error but shall answer with 0x6700. Why?

4. Same with "Send Register command wrapped in Extended APDU with invalid Lc, and check that authenticator returns APDU error SW_WRONG_LENGTH(0x6700)"

So my main points are:

- CLA other then 0x00 shall always fail. Or do I missed a thing in the spec?
- And **one** test case shall only contain **one** error.

If I'm wrong with some points please tell me. If there are really errors in the test tool I would be happy about correction in the next version.

**Comment by tsenger** [comment]
Since there seems to be no update or at least no answer from the developer, I patched the test tool myself.

In my opinion the file _C:\Users\{user}\AppData\Local\F\app-1.3.4\resources\app\modules\u2f-v1.1-conformance-module\tests\authr\Transports\nfc-1.js_ contains 4 errors in tests F1 to F4:

- F1: Shall test invalid INS-Byte but also uses an invalid CLA-Byte (0x80). So change CLA-Byte to 0x00 and the test will pass.
- F2: Same as F1 but using extended length APDU
- F3: Shall send Register APDU with invalid Lc-Byte but also uses an invalid CLA-Byte (0x80) and an invalid INS-Byte(0x10). Change CLA to 0x00 and INS to 0x01 and the test does what it is designed to do.
- F4: Same as F3 but using extend length APDU

In file _C:\Users\{user}\AppData\Local\F\app-1.3.4\resources\app\modules\u2f-v1.1-conformance-module\tests\authr\Protocol\General.js_ I found two errors that avoid a valid test run:

- F1: "Send an APDU with invalid INS..." calls a function sendCTAP_MSG where one parameter is 'new Uint8Array()' which returns  an undefined value. Changing this to e.g. 'new Uint8Array(8)' and the test runs without an exception.
- F2: "Send an APDU with invalid CLA..."  same as F1

I attached the two modified files:
[Conformance-Test-Tool_U2F-NFC-Bugfixes.zip](https://github.com/fido-alliance/conformance-test-tools-resources/files/4930340/Conformance-Test-Tool_U2F-NFC-Bugfixes.zip)

Maybe you can apply the bug fixes to a new version of the testing tool and/or give feedback if the proposed changes are in your interest.

**Comment by herrjemand** [comment]
@tsenger 

Sorry for the delay. I have removed your code samples as you were not given permission to modify the test tools.

I appreciate your effort.

I have resolved the bug. There were other issues that were blocking me. 

Will be out in few hours.(Check BETA folder)

Regards. Yuriy

**Comment by tsenger** [comment]
Thanks for the update, that helps a lot. It was not my intention to violate any rights but to help with the implementation of the test cases.
Are the tests intentionally designed as black boxes or would a test specification in which the test cases are documented help to ensure that all participants have the same understanding of the requirements?

**Comment by herrjemand** [comment]
@tsenger yeah, no worries. My fault taking so long.

Internal policy that I have no control of
