### ISSUE TITLE
BLE Authenticator option is not available

### ISSUE THREAD

**Issue by snakeye** [fido-alliance/conformance-test-tools-resources#560]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?

1.3.4 and 1.4.10

## What is the OS and the version are you running?

Windows 10

## Issue description

I don't have the option to use BLE Authenticator, see the screenshot. 

![image](https://user-images.githubusercontent.com/1873784/81473632-151b7e00-9200-11ea-9fb0-cd9371279d90.png)

Tried all the available versions, including experimental one. Tried to run the tool as an administrator. Tried to install VC Redistributable offered by the tool. No result.

**Comment by herrjemand** [comment]
https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/1.4.40/
