### ISSUE TITLE
Comformance tool cannot read  characteristicses of BLE authenticator.

### ISSUE THREAD

**Issue by shdbk** [fido-alliance/conformance-test-tools-resources#562]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

U2F v1.1

## What is your implementation class?

Authr

## What is the version of the tool are you using?
1.3.4

## What is the OS and the version are you running?
window10 64bit version 1909

## Issue description
The conformance tool cannot read characteristicses of BLE authenticator. I ran the tool as an administrator.
![errorBLE](https://user-images.githubusercontent.com/65533233/82402488-b3240980-9a86-11ea-9a58-006dc8c71276.jpg)

**Comment by snakeye** [comment]
I am sorry to ask here, but how did you manage to get BLE authenticator working in the tool?

**Comment by shdbk** [comment]
Hi snakeys,
1st, You have to connect or pair BLE authenticator to the laptop (condition is the laptop has BLE) in "Bluetooth and other devices settings". Then, you run the tool and authenticator, you will see the BLE authenticator's name on the tool. You can choose it and run the test.

**Comment by snakeye** [comment]
Unfortunately, it did not help. The BLE authenticator is paired but I do not have this option in the tool, regardless I run it as administrator or not. The same computer under Linux works fine but there is no Conformance Tool.

**Comment by herrjemand** [comment]
@snakeye @shdbk try https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/1.4.20/

Sorry for the delay. I lot of work need to be done for this tool.

**Comment by snakeye** [comment]
Thank you, it seems to be working for me now.

**Comment by herrjemand** [comment]
@snakeye Could you test this one? https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/1.4.40/

**Comment by snakeye** [comment]
Tried, works for me. Works even better than before - now I do not need to pair the device to have it visible in the tool. Thank you very much!

**Comment by herrjemand** [comment]
@snakeye did you test it on windows?

**Comment by snakeye** [comment]
@herrjemand, Yes, the tool works both with Windows and Mac OS. Both versions ask to pair the device if it was not paired before.
