### ISSUE TITLE
https://fidoalliance.co.nz/ should not block User-Agent header-less access

### ISSUE THREAD

**Issue by ynojima** [fido-alliance/conformance-test-tools-resources#569]
## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/wiki) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 1.0

## What is your implementation class?

- [x] Server

## Issue description

While running "Metadata Service Tests", TOC files and MDSROOT.crl (https://fidoalliance.co.nz/mds/crl/MDSROOT.crl) need to be fetched, but https://fidoalliance.co.nz returns 403 error with "error code: 1010" when a client access without "User-Agent" header.
This is an error raised by Cloudflare Browser Integrity check.
https://support.cloudflare.com/hc/en-us/articles/360029779472-Troubleshooting-Cloudflare-1XXX-errors#error1010

As user agent requirement is not defined in FIDO MDS specification, this guard should be removed.
I'm writing a MDS client in Java, and Java automatically retrieves CRL file without user-agent header while validating certificate trust chain, and this barrier is hard to remove by client.

## Solution proposal

Disable Cloudflare Browser Integrity check for "https://fidoalliance.co.nz" (it is enabled by default).

**Comment by herrjemand** [comment]
@ynojima Should be resolved now. Please try again

**Comment by ynojima** [comment]
Thank you for changing the configuration. Now it resolved!

**Comment by herrjemand** [comment]
Any time @ynojima
