### ISSUE TITLE
Verifying key chain fails in new version of test tool

### ISSUE THREAD

**Issue by tsenger** [fido-alliance/conformance-test-tools-resources#571]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 1.0
- [ ] UAF 1.1
- [ x] U2F 1.1

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.4.14

## What is the OS and the version are you running?
Windows 10 Pro Release 2004

For desktop tools
- [ ] OSX
- [x ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

In new version 1.4.14 of the testing tool the test case U2F-Register-1 Test authenticator process Register command P-3 fails. In previous version this test case run without an error. I have compared the APDU and responses and there a no differences except the random nonces and signature. So the attestation certificate is read correct and the root certifcate is also correct and they match. 
It iseems that the "verifyCertifiateChain" returns a different value then in the previus version of the test tool. 
Could it be that this error has something to do with the wrong characters for the check marks and x? May be a problem in the charset?
All other tests regarding to issue #557 are running now without errors.

**Comment by tsenger** [comment]
Here are two screenshot to see the difference.

Version 1.4.14:
![screenshot_v1 14 4](https://user-images.githubusercontent.com/6859154/89037355-9c2f4c80-d33e-11ea-8bfa-d38c14c11fc1.PNG)

Version 1.3.4:
![screenshot_v1 3 4](https://user-images.githubusercontent.com/6859154/89037356-9cc7e300-d33e-11ea-8af8-99eef733db4c.PNG)

**Comment by herrjemand** [comment]
Hey @tsenger. Could you preset me your metadata and authenticator response?

**Comment by tsenger** [comment]
Sure. This is the communication log for the test case:
```
Test started: P-3

        Send a valid APDU Register command, wait for response, extract attestation certificate, and try verifying it against the attestation roots in the metadata.attestationRootCertificates

    
C:\Users\Tobias\AppD…ports\nfcdep.js:103 Selected protocol "2" for reader "REINER SCT cyberJack RFID basis 0"
C:\Users\Tobias\AppD…ports\nfcdep.js:219 NFC DATA SENT: 00a4040008a0000006472f000100
C:\Users\Tobias\AppD…ports\nfcdep.js:224 NFC DATA RECEIVED: 5532465f56329000
C:\Users\Tobias\AppD…ports\nfcdep.js:192 RECEIVED  SW_NO_ERROR
C:\Users\Tobias\AppD…ports\nfcdep.js:219 NFC DATA SENT: 0001000040f6abda5100a130a180c709422edccf4efa10df8188facb72975b37c1ae793f9f04b30fd49d6c9b51ad5b7ebe84c5ca3867b6eb84c15193cb78d57a0f10a3a2e600
C:\Users\Tobias\AppD…ports\nfcdep.js:224 NFC DATA RECEIVED: 0504026fe7e67248aa01d99559ba71adcfb2c312494381746407d9e5effc1b150edb67697e53fe4cb050239ee28e5ba1a4fc0e0d5b1116b9e81971be182eadbf53d14014175759c2e1516dce9758a4f2263f04121384f66affcff136ec197fc49dececefc209a6050bf54c6c6dd3be8be1faa2b3446d3b2c88a793f12d06e5e3f28b60308201433081eaa003020102020104300a06082a8648ce3d040302301f311d301b06035504031314425349204649444f2055324620526f6f74204341301e170d3139303430333039323130305a170d3238303430333039323130305a3029312730250603550403131e64652e666163322055324620746f6b656e2056656100
C:\Users\Tobias\AppD…ports\nfcdep.js:192 RECEIVED  SW_BYTES_REMAINING_00
C:\Users\Tobias\AppD…ports\nfcdep.js:207 Bytes remaining:  0
C:\Users\Tobias\AppD…ports\nfcdep.js:219 NFC DATA SENT: 00c0000000
C:\Users\Tobias\AppD…ports\nfcdep.js:224 NFC DATA RECEIVED: 7273696f6e20312e33343059301306072a8648ce3d020106082a8648ce3d0301070342000442f66dd0b405ff4ed828f606ce91f191af2126ec8cc49effe13c1d4c452ed8ca32868736a1685ae2f7fd97ae5be0812bb7d75b74b9d776d486c7c3c68ca7b08fa30d300b30090603551d1304023000300a06082a8648ce3d04030203480030450221008f332d0dcffae70378dbc38f9f26f61d60c8e86db7fd4cd417b71a456662834c022009f2ac2abd1079d170b27290f1a9017eac0e5514b3173e8f0cf151bc608b26d43046022100e7140bd4ad153f30bfb734d3f1c4eb2feea881269b975afb3a3ffd0bcd8913be022100ea1e183179ea21327eb71ab7b6c46112
C:\Users\Tobias\AppD…ports\nfcdep.js:192 RECEIVED  undefined
C:\Users\Tobias\AppD…ports\nfcdep.js:207 Bytes remaining:  18
C:\Users\Tobias\AppD…ports\nfcdep.js:219 NFC DATA SENT: 00c0000012
C:\Users\Tobias\AppD…ports\nfcdep.js:224 NFC DATA RECEIVED: 4edd55f60d62aaae417eadba9e7594a75e029000
C:\Users\Tobias\AppD…ports\nfcdep.js:192 RECEIVED  SW_NO_ERROR
```
The attestation certificate, the root certifcate and the metadata file are attached:
[de.fac2_Test-P3.zip](https://github.com/fido-alliance/conformance-test-tools-resources/files/5022387/de.fac2_Test-P3.zip)

**Comment by Spomky** [comment]
I also have error with the new tool.
I noted that the packed attestation statements contain certificate chains that are not correctly encoded.
See below:

```sh
array:3 [
  "alg" => "-7"
  "sig" => b"0E\x02 \x10iœÇ'D!8ÈƒËo“^T¹l\x03³<·»ëý%¡\x12ý!’³Ò\x02!\x00Äoh"'Èa²f{ö\x1AuÁ¿\x1DûÜB§íégÈèø³oOo¦ý"
  "x5c" => array:3 [
    0 => b"0é\x02Ä0é\x024á\x03\x02\x01\x02\x02\x01\x010\n\x06\x08*åH╬=\x04\x03\x020ü»1&0$\x06\x03U\x04\x03\f\x1DFIDO2 INTERMEDIATE prime256v1110/\x06\t*åHå¸\r\x01\t\x01\x16"conformance-tools@fidoalliance.org1\x160\x14\x06\x03U\x04\n\f\rFIDO Alliance1\f0\n\x06\x03U\x04\v\f\x03CWG1\v0\t\x06\x03U\x04\x06\x13\x02US1\v0\t\x06\x03U\x04\x08\f\x02MY1\x120\x10\x06\x03U\x04\x07\f\tWakefield0\x1E\x17\r180523143741Z\x17\r280520143741Z0ü┬1#0!\x06\x03U\x04\x03\f\x1AFIDO2 BATCH KEY prime256v1110/\x06\t*åHå¸\r\x01\t\x01\x16"conformance-tools@fidoalliance.org1\x160\x14\x06\x03U\x04\n\f\rFIDO Alliance1"0 \x06\x03U\x04\v\f\x19Authenticator Attestation1\v0\t\x06\x03U\x04\x06\x13\x02US1\v0\t\x06\x03U\x04\x08\f\x02MY1\x120\x10\x06\x03U\x04\x07\f\tWakefield0Y0\x13\x06\x07*åH╬=\x02\x01\x06\x08*åH╬=\x03\x01\x07\x03B\x00\x04║┘b¼±¡R/Ü¹\n\fÆ\x1C\x17█Ù:Öôðñúfc¥─§╦‗\x1A¹Çdie\x1CQæâ¶|æ\x0F╠*4e2À\x0FÙÃ\x16█\x1D\x0E\x01¢Wn)Hdú,0*0\t\x06\x03U\x1D\x13\x04\x020\x000\x1D\x06\x03U\x1D\x0E\x04\x16\x04\x14JTÕ\x06ÊæDOm\x0F3]Í²ÃFl╣_T0\n\x06\x08*åH╬=\x04\x03\x02\x03H\x000E\x02!\x00╣[6┤s}ú¼\x10Ë\r¥§ÙòÕ\x04'BZDò\x7F;ßåíË\x7F'ÛE\x02 M\v¼└8@ñ|*O§·[ãÿq╩×£ª²\x1Cí|\fÍæäs7)x"
    1 => b"0é\x0410é\x02\x19á\x03\x02\x01\x02\x02\x01\x020\r\x06\t*åHå¸\r\x01\x01\v\x05\x000üí1\x180\x16\x06\x03U\x04\x03\f\x0FFIDO2 TEST ROOT110/\x06\t*åHå¸\r\x01\t\x01\x16"conformance-tools@fidoalliance.org1\x160\x14\x06\x03U\x04\n\f\rFIDO Alliance1\f0\n\x06\x03U\x04\v\f\x03CWG1\v0\t\x06\x03U\x04\x06\x13\x02US1\v0\t\x06\x03U\x04\x08\f\x02MY1\x120\x10\x06\x03U\x04\x07\f\tWakefield0\x1E\x17\r180723142907Z\x17\r451208142907Z0ü»1&0$\x06\x03U\x04\x03\f\x1DFIDO2 INTERMEDIATE prime256v1110/\x06\t*åHå¸\r\x01\t\x01\x16"conformance-tools@fidoalliance.org1\x160\x14\x06\x03U\x04\n\f\rFIDO Alliance1\f0\n\x06\x03U\x04\v\f\x03CWG1\v0\t\x06\x03U\x04\x06\x13\x02US1\v0\t\x06\x03U\x04\x08\f\x02MY1\x120\x10\x06\x03U\x04\x07\f\tWakefield0Y0\x13\x06\x07*åH╬=\x02\x01\x06\x08*åH╬=\x03\x01\x07\x03B\x00\x04▄A\x1D▀Um\x7FMsî®u\x14zUq¶c\x00)#Ío┤{^ùç pY\x05\x0E╔╬ç®o4WèÈ¦\x08┤┬|ıÚ,MFÞö\▓Ëµ_█KIy¾ú/0-0\f\x06\x03U\x1D\x13\x04\x050\x03\x01\x01 0\x1D\x06\x03U\x1D\x0E\x04\x16\x04\x14g┴\x19ÆÉ[§]\x00┴Í!\x0Eî-v!ÆG└0\r\x06\t*åHå¸\r\x01\x01\v\x05\x00\x03é\x02\x01\x00\vÿ.º│T╗\x07'v'´Õ▄%gíêH¶─r$\x1D3\x19ìú┘─¶\x14@;fÝC@¦%Ïƒ\x03┴ºA\x07v§Ê ô┼8±k£cè│║¶Yh«│Þ\x02+Sf└RRk*ySf°¦ê═Þë6=Y8ü§ýƒÿ»┘ÇK¹[ð─\x15n´«\x1D÷·ÿÊ4]U╦\eî\x12Ö┌ı~¼╩½M\rQ¥├F\vì┘\x17ïG"╣\x12rÐ\x0F@¸Kµ0¿\x00ã\tÐ|*%Õñ\x14özY18è¹├éº╦\x12ó¡9@¦²ï-°╗Ç\x1E(e\x16zÔú`L\r▓\x02áƒÙ§°\r]mL6qf þsóµo├@╣m¨k5åë.┴|BzFü¥'ü÷{Á¦÷\x17┐┤ñâ\vû<▄2\x14¨PæjH>\x06²yô\x04ÌIÈêØä\x01-T\x13╣+ic`¦─\x0E┌■¡cn>þßf\x13+ûèqéå▒ý┴=,b┘í@iVkF┬WÎ─,¥¢l#║ß\x18ûíÚ╦▓%§µ\x19ª\v┐Öl_CıQÒÈ\x11Ð§Þ¿\x01ò\x15óq"\föÖ\x1Eıq^YöÌ4\x01å▒\x0F╬ÐyF~╗Ð▄Û³N\x07,¸¾n▓û°¢à┌/û\x11a{rÏ£5PA-u\x07░P/\x19â*┐░─Ë0ãi×╦·5╚ì ó\x13b#ï\x10í1î?hV0ø\x1D\rÙ+ùxÉÏ╗Ã┬IsèL¶ze\e\v\t\r³ÁqRA\x1Cºı>Eé³]│┤6│\x18-Upì╦┴Lóç÷¯\x08╠╗ÿ©ñ\vvòı─;\x1Ds#c■6■å\x17\x166S­m\â"
    2 => "MIIFwDCCA6gCCQCNm1u56oRwXTANBgkqhkiG9w0BAQsFADCBoTEYMBYGA1UEAwwPRklETzIgVEVTVCBST09UMTEwLwYJKoZIhvcNAQkBFiJjb25mb3JtYW5jZS10b29sc0BmaWRvYWxsaWFuY2Uub3JnMRYwFAYDVQQKDA1GSURPIEFsbGlhbmNlMQwwCgYDVQQLDANDV0cxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJNWTESMBAGA1UEBwwJV2FrZWZpZWxkMB4XDTE4MDMxNjE0MzUyN1oXDTQ1MDgwMTE0MzUyN1owgaExGDAWBgNVBAMMD0ZJRE8yIFRFU1QgUk9PVDExMC8GCSqGSIb3DQEJARYiY29uZm9ybWFuY2UtdG9vbHNAZmlkb2FsbGlhbmNlLm9yZzEWMBQGA1UECgwNRklETyBBbGxpYW5jZTEMMAoGA1UECwwDQ1dHMQswCQYDVQQGEwJVUzELMAkGA1UECAwCTVkxEjAQBgNVBAcMCVdha2VmaWVsZDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAL11U5yAIVLMrL3xS8u8ysMSdOkDeoTO+RcAy+uXXp6k4SC+jOy37gICEtYI+MKQV1EMeMMf3rM1ueZAO3iPFa0NEdi/oQ7npnGjBNI8wMzD8FfNe6rWtzkDaHpsZW///MwWDpGyJR+Xyjcq6U4vS9bS6zZ7jslw0Oczx4UsYgOsIUXSSBaGOrRbxJ/JC5gnDYEYvtNM+PDPczLNKAyhdvBZWNWHr7MZ0P5TeJQcXsAoShRX2Y8U8fRNJm7SeiFKDP0Nn/QKxOSt7zGP4xt9nMasE1q2ZTdar2+W13CRz37RI0ZWpq/+YquoEbZ7Uj7NmBTcqhb260nmDER2FpwwYwPSark92IZbamozB8d7OEI1jJgsrjJhKan0EmRaWVBpHT4xYKdEu7r09S0JhKyU+52WDmmVQTMpYLrm4Xl7hRxyPyBYkalrozsGmPs8vlhNq3VsVbyBSMSpEmUaeAa7LLE9/Vh0agJLVFHh1ehYKJpzHnmmBXUqx0Fz3afmDm1NX0sr3O/6xIx1VSTViT3KNxBYpVH1qjHATLzuxcWmm+75fcJMiPYPSMXVmRb3Q1l91AM4BBeWhlP3Fbc7gDy0r+s7m0sGS6PT2J2rGog2rUxnJ+zCM11M7DeO0XM2nny4uRYPPk9w2EXzfvtdvieYU/5RB4RDm5TGxHhGXVZUgac5AgMBAAEwDQYJKoZIhvcNAQELBQADggIBAFt2XGd3k5GpbO1EUm3u60zT1fE6u6pOscp156k5VnsHgaHRHdIAPNLeLNmR7y5OnrXbh13CrGwU1q84jjJXpv+v14xUCc5i01yopFTQFLr4A7NHp2nNYfNhhIVSFAgW43EflJflbLEelCJzxLlWb5BoDsZeeNmEQsXIM1mJ26R3r0dzsHBb0uy+8LNR1gdVqdjhC8BLy3gh4+BWuidyZNt07LveDsSFW5rcj5wRrSx9hXPIyVpjQSljNvY7MVTouqJzNAAQMsTKkXPkTXldCop9Qo9UPkHRRm0l7LLtdaOoXrct0Ymocf8zxf9bFNiw9f4WRYQM6sMhzt8+s/oDilo4QhcUgeJEiEPESi6ynYTV62SHA4eMunUJ5dlCaRnFiR9DTImFa5IRzie326/nW/SPCaKc/yrFIihMMjJoSAPhpTb/K6yHOUG8r+KiQut7NzqGV301pQ9u62dGL5Oi1VXmCFlE2ramZs15BNOUyAo2CBbRJg3jKcdu/8QC6ojjDvQ863+7LPtn74wJC5RpUJsS0GhQWgq5pAXO3wA61Uobxi6MkOpCC0zBWx/d4CqpS4j4hFgxWBTXX48ihPu+hIxIF/AxbqtPvqLMExW/xZITn6ArpWyQ9e4SUVr3n3F33ap1XdDyZ0vwFcm18JQAtsvXT6qCLrWOXnHUgfn/+Viu"
  ]
]
```

The first and second certificates are binary strings when the last one is already base64 encoded. It should be a binary string as well right?
This breaks some tests e.g. when the full chain is in the attestation.

**Comment by tsenger** [comment]
Hey @herrjemand is there any progress in the investigation of the problem?

**Comment by tsenger** [comment]
Okay @herrjemand, I have a clue whats wrong:
The function _verifyCertificateChain_ in app/js/utils.js changed from previous test tool version in one point. The default value of variable _valid_ changed from **true** to **false**. Thats seems to be okay because if any error occurs the function will not return just true which means the cert chain is valid. 
But there is this line 401 that causes  the return value to be **always** false:
`valid = valid && Signature.verify(signatureHex); // true if CA signed the certificate`
See, false AND 'any value' will always be false.
Second point is this line 385 in app/js/utils.js:
```
    if(i + 1 >= certificates.length) {
        CACert = Cert;
    } else if(certificate.getSubjectString() !== certificate.getIssuerString()) { // If only intermediate given
       break
    } else {
        CACert = certificates[i + 1];
    }
```
The function _verifyCertificateChain_ will be called from modules/u2f-v1.1-conformance-module/tests/authr/Protocol/Registration.js like this:
```
  let certificatePath    = [batchCertificateBase64, attestationRootBase64];
  let certificatePathPEM = certificatePath.map((certificateBase64) => base64StringCertToPEM(certificateBase64));

   if(verifyCertificateChain(certificatePathPEM)) {
       passed = true;
       break
   }
```
So cert[0] is the attestation certificate (batchCertificateBase64) and cert[1] is root certificate (attestationRootBase64). With these parameters we come to line 387 where "certificate" is cert[0] (attestation certificate). In the in attestation certificate Subject and Issuer shall not be equal (because the root is the issuer). So this line causes the break in line 388 which should be happend. 

I don't know how you use the _verifyCertificateChain_ function in other test case. But for the U2F test this is the point where are some improvements are needed.

**Comment by tsenger** [comment]
Hi there @herrjemand, 
I created a patch for the utils.js. 
[utils.js.diff.zip](https://github.com/fido-alliance/conformance-test-tools-resources/files/5168883/utils.js.diff.zip)
With that the _verifyCertificateChain_ function should work as intended. Maybe it helps to improve the test tool.
Best regards

**Comment by herrjemand** [comment]
@tsenger I think I mentioned last time, and I will clarify again. Do not modify the tool. FULL STOP

The tool works as expected. The issue you are having is that you have full chain in your attestation. The server verifies attestation chain from the authenticator against the attestationRootCertificates in the metadata. So if you have full chain, the tool will try to append certificate to the chain, which means you will have TWO root certificates in the chain, which is violating RFC5280 processing rules.

I deeply apologise for slow reply. I am only on the part time bases, and we had a major issue with our BLE stack, which massively blew up my schedule and ability to pro-actively respond.

However.

If you at any point have modified the tool. And have submitted results with the modified the tool.

1) Remove any modifications. Delete the tool. And download fresh copy. I will add new screaming EULA next version just to remind that when you applied for access to the tools.
2) Email certification@fidoalliance.org to avoid potential penalties. I am happy to ignore this whole thing on the bases that I was really slow.

Hope this clarifies the situation

**Comment by tsenger** [comment]
I understand you are not amused. But I still think that the stable version 1.3.4 sent wrong command APDUs which were fixed in experimental version 1.4.14. Thanks for that.

Then there is only this one open issue for the certificate validation in v1.4.14:
You wrote the authenticator sends a certificate chain which contains the root and that this would be the problem.
I inspected the communication log which I sent before in detail and as you can see there is only the attestation certificate without the root in response to the registration command APDU (turquoise marking):
![de fac2_attestation](https://user-images.githubusercontent.com/6859154/92576587-fdc1cf80-f289-11ea-9e41-f582ae7d8b16.png)

Do I miss something?

**Comment by herrjemand** [comment]
Please try https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/1.4.40/

**Comment by tsenger** [comment]
Hi @herrjemand 
seems to work now. All tests passed. But I can't submit the results: "Error while submitting the results".

**Comment by herrjemand** [comment]
@tsenger Relates to #578 

Almost done wit that
