### ISSUE TITLE
Conformance-test-tools : Failed to read metadataTOC.

### ISSUE THREAD

**Issue by midaslmg94** [fido-alliance/conformance-test-tools-resources#572]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 1.0
- [ ] UAF 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [x]  Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.3.4

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

One error occurred when using FIDO Performance Tools v1.3.4 (FIDO2 ). Everything except this has passed.

> Error: Server responed with error. The errorMessage is: Failed to read metadataTOC. 
session = JmxqJwNE8q85Pbn7iCVdYKcnPoKt3NGkmhmSFaS-65Y

The address entered for TESTS CONFIGURATION is `http://localhost:8080/fido2` . I don't know if it's because https isn't applied or because it's localhost.

I would like to apply for the IOP Test in September. If there is only one error in the performance tool above, can I apply for the IOP test using the domain with https applied? 

And can I get and use a certificate issued by a site such as Let's encrypt or a free SSL when applying ssl?

**Comment by herrjemand** [comment]
@midaslmg94 

Yes, you can use Letsencrypt

Try resubmitting your serverURL

**Comment by herrjemand** [comment]
@midaslmg94 P.S. Apply for interop, and just mention that you had tools issue
