### ISSUE TITLE
U2F HID: Conformance Tool does re-send request after response was sent by device

### ISSUE THREAD

**Issue by gddcgmsrd41ud** [fido-alliance/conformance-test-tools-resources#574]
## What protocol are you implementing?

 U2F 1.2

## What is your implementation class?

Security Key / FIDO2 / U2F authenticators

## What is the version of the tool are you using?

1.3.4

## What is the OS and the version are you running?

Windows 10, Version 1809

## Issue description

Conformance Tool does re-send request after response was sent by device. Conformance Tool’s receive method doesn’t do a count down of frames as announced by initialization frame of response (length field), but “relies” on a timeout after response was received. Conformance Tool must not re-send the request if getting a timeout but response already received. Note: in case of FIDO2 HID the request re-send is disabled, but receive method still waits for timeout to finish.

**Comment by gddcgmsrd41ud** [comment]
Suggested patch:

`fido-conformance-tools-electron-win32-x64-1.3.4\app-1.3.4\resources\app\dependencies\transports\nodehid.fork.js`
`*** 359,371 ****`
`!                     } else {`
`--- 359,371 ----`
`!                     } else if(!results.length) {`

**Comment by xchapron-ledger** [comment]
@herrjemand Hello, I'm also facing this issue with Conformance tool version 1.7.0.
Are you planning to address this issue in a future release?
Thanks.
