### ISSUE TITLE
Windows: Subscription for BLE Status Notifications, test tool should wait

### ISSUE THREAD

**Issue by gddcgmsrd41ud** [fido-alliance/conformance-test-tools-resources#575]
## What protocol are you implementing?

 FIDO2

## What is your implementation class?

Security Key / FIDO2 / U2F authenticators

## What is the version of the tool are you using?

1.3.4

## What is the OS and the version are you running?

Windows 10, Version 1809

## Issue description

We are implementing a FIDO2 BLE authenticator. The PING test case is getting a timeout. We see that PING cmd is received before 'fido-Status' characteristic is subscribed. As per the specification 'fido-Status' (notify) should be subscribed first then only we can respond to any command.

**Comment by herrjemand** [comment]
@gddcgmsrd41ud Try https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/1.4.20/

**Comment by herrjemand** [comment]
New build https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/1.4.40/
