### ISSUE TITLE
CTAP2 BLE PING test returned error.

### ISSUE THREAD

**Issue by imaec** [fido-alliance/conformance-test-tools-resources#577]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- FIDO2 1.0

## What is your implementation class?

- Android FIDO2 authenticators

## What is the version of the tool are you using?

- 1.4.14

## What is the OS and the version are you running?

- OSX & Android authenticator

## Issue description

I'm implementing a fido2 BLE authenticator.
When I ran the fido-conformance-tool PING test(P-9 on Test CTAP2 BLE support) is getting error.

Only onDescriptorWriteRequest is executed in the authenticator's BluetoothGattServerCallback and responds with 
`mGattServer.sendResponse(device, requestId, BluetoothGatt.GATT_SUCCESS, offset, value)`

screen shot.
![스크린샷 2020-09-03 오후 4 15 09](https://user-images.githubusercontent.com/30709024/92086297-f7a09e80-ee04-11ea-9bb0-2b8082134c1a.png)

I want to know the cause of the problem.
Is there any way to solve this problem?

_*Please understand that not good at English._

**Comment by herrjemand** [comment]
@imaec Try https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/1.4.20/

**Comment by imaec** [comment]
Thanks for answer first!

I tried with version 1.4.20 also failed.
This time the error occurs on P-1.

screen shot.
![image](https://user-images.githubusercontent.com/30709024/92565104-23180300-f2b5-11ea-805c-017e27da9e1f.png)

help me please..

**Comment by herrjemand** [comment]
@imaec are you sure that's 1.4.20?

<img width="212" alt="Screenshot 2020-09-09 at 21 12 16" src="https://user-images.githubusercontent.com/1636116/92630599-25905200-f2e1-11ea-8215-0c51546d89e5.png">

**Comment by imaec** [comment]
@herrjemand Yes, I installed it as 1.4.20, but it is displayed as 1.4.15 in the tool.
![스크린샷 2020-09-10 오전 10 10 14](https://user-images.githubusercontent.com/30709024/92671383-12b56600-f351-11ea-9a79-37ffe2d91710.png)

And the correct version is displayed in the Tools information.
![스크린샷 2020-09-10 오전 10 34 02](https://user-images.githubusercontent.com/30709024/92671466-54dea780-f351-11ea-99f3-8ec53787799d.png)

**Comment by herrjemand** [comment]
@imaec https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/1.4.40/

**Comment by imaec** [comment]
@herrjemand 
Tested with 1.4.40 version and solved!
Thank you.

**Comment by herrjemand** [comment]
Great @imaec!

Please upgrade to 1.5.0.

I have tweaked timeouts, so it works much better with longer tests https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.5.0/

Additionally we've moved to new infrastructure, so you will need it to submit results.
