### ISSUE TITLE
POST https://fidoalliance.co.nz/register net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by stephenWebComm** [fido-alliance/conformance-test-tools-resources#579]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 1.0
- [x] UAF 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [x] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [x] Android

## Issue description

when running UAF1.1 tests get below error
<img width="934" alt="註解 2020-09-18 113753" src="https://user-images.githubusercontent.com/40379850/93552588-694f1f80-f9a3-11ea-93b4-e006601d3d7f.png">

**Comment by stephenWebComm** [comment]
maybe same problem #578

**Comment by herrjemand** [comment]
@stephenWebComm yeah.

Closed as dublicate.
