### ISSUE TITLE
Make status and errorMessage optional on success

### ISSUE THREAD

**Issue by pmlopes** [fido-alliance/conformance-test-tools-resources#580]
When working with FIDO2 server tests, for successful responses, the test application expects a json object with:

```
status: "ok" ,
errorMessage: ""
 ```

For the end user these fields are of no real use and we can agree that on error they are useful. Perhaps we could relax the verification for responses with status code 2xx.

In my case I need to patch the webauthn responses to comply with the tool but when running live without those fields the protocol still works as expected as the webauthn don't really mandate them.

**Comment by herrjemand** [comment]
@pmlopes this is only for conformance testing. You are free to remove that in production. I would really prefer not to break backwards compatibility with the existing solutions
