### ISSUE TITLE
support for handling "batch self signed attestation certificates"

### ISSUE THREAD

**Issue by equalsJeffH** [fido-alliance/conformance-test-tools-resources#581]
Please add support for handling "batch self signed attestation certificates"  (e.g., as emitted by present G Titan Security Keys). 

See also: https://github.com/fido-alliance/mds-specs/issues/77

**Comment by herrjemand** [comment]
@equalsJeffH as soon as you guys retrospectively approve the change within WebAuthn and FIDO2 TWG, we will certainly do that

**Comment by equalsJeffH** [comment]
see https://github.com/w3c/webauthn/pull/1499

the ctap spec is not involved here.

**Comment by equalsJeffH** [comment]
Here is the applicable error FIDO Conformance Tools v1.5.2 (U2F 1.1) is giving:

P-3 Send a valid APDU Register command, wait for response, extract attestation certificate, and try verifying it against the attestation roots in the metadata.attestationRootCertificates‣

Error: Certificate path contains dublicate certificates! Please check that authenticator does not return full chain it its response!
    at Proxy.verifyCertificateChain (js/utils.js:397:15)
    at eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:2768:24)
