### ISSUE TITLE
New version Tool Execute Error

### ISSUE THREAD

**Issue by devjhseo** [fido-alliance/conformance-test-tools-resources#582]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 1.0
- [x] UAF 1.1
- [x] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.5.0

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
I was download new version 1.5.0 Tool's setup. and I was success for installed.
but It doesn't work. I can't execute Test Tool.

![error](https://user-images.githubusercontent.com/72909504/96095402-81b24b80-0f09-11eb-96f0-f78f1dbab1f0.JPG)

**Comment by pmlopes** [comment]
I can confirm that on virtual box and on a second physical machine it doesn't work for me either.

Tested windows 10 (pro + home)

**Comment by herrjemand** [comment]
Ok, fixed in the new build.

https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.5.1/

Sorry for that

**Comment by devjhseo** [comment]
I have checked for new update.

But it still has this problem. I think this problem has existed since version 1.4.15.

**Comment by herrjemand** [comment]
@devjhseo I am struggling reproduce this error. When does it happen?

**Comment by devjhseo** [comment]
Occurs during the execution phase after installation is complete. and It happened every time it is run.

**Comment by devjhseo** [comment]
Did you update the Javascript version?

**Comment by herrjemand** [comment]
@devjhseo Do you have firewall or something?

**Comment by devjhseo** [comment]
@herrjemand Yes, but I turned off the firewall. and the result were the same.

My Windows Version (Windows 10 Pro - 1909)

**Comment by devjhseo** [comment]
@herrjemand  I solved this problem.

I think this problem appears in higher versions of Windows. 
If you just run the tool, an error occurs. but if you run as administrator the tool, It works.

Tested v1.5.1 Tool

**Comment by herrjemand** [comment]
@devjhseo Yes, FIDO2 tools must only be run as administrator on windows. I will take a look and make sure it is explained properly
