### ISSUE TITLE
Certified authenticators with un escaped , in CN causing problems with parsing. 

### ISSUE THREAD

**Issue by ve7jtb** [fido-alliance/conformance-test-tools-resources#583]
I had AOL reach out to me because they are seeing one authenticator with a malformed batch certificate. 

There is apparently a Fido2 certified authenticator with a invalid CN.

They are seeing:
"CN=\"value1, Ltd\", O=value2, C=value3".

They don't want to say who it is specifically.  

They want to know how we didn't detect and invalid batch certificate if it is certified?

They are going to code a work around, but suggest we check that going forward.

**Comment by herrjemand** [comment]
Production certificates are outside of the scope of the certification. Our validator would catch that, but it does not stop vendors from generating bad pki in production.

Suggest contacting vendor.
