### ISSUE TITLE
Metadata TOC from mds.certinfra.fidoalliance.org contains CRLDP referring to an invalid domain

### ISSUE THREAD

**Issue by dayasakti-2020** [fido-alliance/conformance-test-tools-resources#584]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 1.0
- [ ] UAF 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [x] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.5.1

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows 10
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

### Summary
Metadata TOC from mds.certinfra.fidoalliance.org contains CRLDP referring to an invalid domain fidoalliance.co.nz.
Due to Metadata TOC certificates having invalid CRLDP, Metadata Service Tests are unable to pass completely.

### Steps
1. register a fido2 server endpoint `https://fido2.test`
2. received one of Metadata ToC URL `https://mds.certinfra.fidoalliance.org/execute/1d52d7b7a879443f3c3b27451da064e9d898c61ba68127b2be418fb8188bdc42` with the content pasted here: https://gist.github.com/dayasakti-2020/1d7ef8037d0fb170a2e23a2f4b844390
3. the Metadata TOC is a JWT header with certificates in the x5c field having CRLDP shown something like below
```
X509v3 CRL Distribution Points: 

                Full Name:
                  URI:https://fidoalliance.co.nz/mds/crl/MDSCA-1.crl

            X509v3 Certificate Policies: 
                Policy: 1.3.6.1.4.1.45724.1.3.1
                  CPS: https://fidoalliance.co.nz/mds/repository
```

**Comment by herrjemand** [comment]
@dayasakti-2020 Ref: https://github.com/fido-alliance/conformance-test-tools-resources/issues/578#issuecomment-704945111

I will upload a build in few hours

**Comment by dayasakti-2020** [comment]
Thanks @herrjemand after re-registering the server endpoint and getting the new MDS TOC URLs, the CRLDP now looks correct
```
            X509v3 CRL Distribution Points: 

                Full Name:
                  URI:https://mds.certinfra.fidoalliance.org/crl/MDSROOT.crl

            X509v3 Certificate Policies: 
                Policy: 1.3.6.1.4.1.45724.1.3.1
                  CPS: https://mds.certinfra.fidoalliance.org/repository
```

**Comment by herrjemand** [comment]
Awesome! Glad to hear.

Try new build as well https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.5.2/
