### ISSUE TITLE
Version shown from the FCT 1.5.2 does not look correct

### ISSUE THREAD

**Issue by dayasakti-2020** [fido-alliance/conformance-test-tools-resources#585]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 1.0
- [ ] UAF 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [x] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

1.5.2

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows 10
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

1. I tried installing 1.5.2 as mentioned in [this reply](https://github.com/fido-alliance/conformance-test-tools-resources/issues/584#issuecomment-722049708) . I used this installer https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.5.2/Setup%20-%20FIDO%20Alliance%20-%20Certification%20Conformance%20Testing%20Tools%201.5.2.exe

1. Installation is successful. Windows sees it as version 1.5.2. ([Click here for the screenshot](https://gist.github.com/dayasakti-2020/426d73d8c93edae041bfa7dc6eb6c65c#file-installed-png)) 

1. When I run FCT, it shows as version 1.5.0. ([Click here for the screenshot](https://gist.github.com/dayasakti-2020/426d73d8c93edae041bfa7dc6eb6c65c#file-displayed-png))

1. That said, I don't see any issues while running the tests. However, I would like to know whether I have correctly installed FCT 1.5.2 and the tests that I run is indeed version 1.5.2? And the incorrect version shown is **a matter of incorrect display on the tool only**?

**Comment by herrjemand** [comment]
@dayasakti-2020 Fixed in the latest build

Sorry had an issue with our script

**Comment by dayasakti-2020** [comment]
@herrjemand Thank you for the swift response. I now see the correct version when running FCT 1.5.2.
