### ISSUE TITLE
BLE Authenticator Connect Problems and false RSSI

### ISSUE THREAD

**Issue by roben-cg** [fido-alliance/conformance-test-tools-resources#588]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 1.0
- [ ] UAF 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.5.2

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows 10 2004
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
I'm running conformance tests for an BLE authenticator. Often I can see a false connection status and RSSI value, even if the device is connected e.g. with -64dB (checked with Bluetooth LE Explorer).

![Bildschirmfoto vom 2020-11-17 13-29-53](https://user-images.githubusercontent.com/74362707/99390824-918ec800-28d9-11eb-8d9b-360cf0fe4705.png)

However, sometimes I can "reconnect" the device without seeing the correct connect status, but I can run the tests. Sometimes the connect status is shown correctly. Often I need to start Bluetooth LE Explorer to force BLE connect.

![Bildschirmfoto vom 2020-11-17 13-45-53](https://user-images.githubusercontent.com/74362707/99392030-59888480-28db-11eb-8248-12a688db3e46.png)

In the middle of some tests, this message can be found in the inspector: `Skipping connecting to peripheral with UUID(680ae2f17fe7). Peripheral is too far away. Device RSSI is -127. Min RSSI is -80.`

I cannot run ClientPin1 tests without seeing timeouts due to very long BLE reconnect times.

**Comment by herrjemand** [comment]
@roben-cg If you open menu, there is an advance config. You can set RSSI threshold in there.

![Screenshot 2020-11-29 at 22 36 31](https://user-images.githubusercontent.com/1636116/100552962-69b54200-3293-11eb-935b-3d5ba524390e.png)

Unfortunately we rely on WinRT, and it can be buggy sometimes. I suggest not using Bluetooth LE Explorer together with the tool, as I found that i can cause the RSSI issue(Windows is weird).

**Comment by roben-cg** [comment]
Can you provide the conformance tests tools for Linux (Debian 10/11 or Raspi)? Then it would be more clear for me where a bug comes from, WinRT or my device.
