### ISSUE TITLE
Conformance tools installation fails when installing on non-latin operating systems

### ISSUE THREAD

**Issue by herrjemand** [fido-alliance/conformance-test-tools-resources#589]

**Comment by Kojiro-Goto** [comment]
Hello @herrjemand ,

I got similar issue.

I got a javascript error when I run ~v1.6.18.exe and while running msi installer. Please see captured below.

<img width="563" alt="v1_6_18_exe" src="https://user-images.githubusercontent.com/32250000/111140204-6ab17b80-85c5-11eb-9cbb-504b5dd4d585.png">

Do you have any workaround?

**Comment by Kojiro-Goto** [comment]
Alternatives:
1. Create non multibyte language account
2. Change language settings while installation and running this tool.
