### ISSUE TITLE
U2F - Conformance Tool resend request error.

### ISSUE THREAD

**Issue by devjhseo** [fido-alliance/conformance-test-tools-resources#590]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 1.0
- [ ] UAF 1.1
- [x] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.5.2

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

Authenticator did not send response(Error Code - SW_CONDITIONS_NOT_SATISFIED or Anything), after authenticator received first request.
But, conformance-test-tool keep resend request regardless of response.

**Comment by herrjemand** [comment]
@devjhseo the tools is trying three times the same test to make sure that it wasn't one transport issues.

What issue are you having?

**Comment by devjhseo** [comment]
@herrjemand The request and response must match each other one-to-one. If the response cannot be submitted within a short period of time, the previous response is recorded in the next request.
