### ISSUE TITLE
U2F - Experimental v1.5.21 tool's Data read Error 

### ISSUE THREAD

**Issue by devjhseo** [fido-alliance/conformance-test-tools-resources#594]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 1.0
- [ ] UAF 1.1
- [x] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
Experimental v1.5.21

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
In new part of Authentication Test (P-4), conformance-tool received just one line of HID DATA.
Regardless of the length of hid data sequence, only one line of the sequence is received.

so, tool cannot parse response structure and UP.

**Comment by devjhseo** [comment]
P-4 working HID DATA READ func, not HID DATA RECEIVED func.

**Comment by herrjemand** [comment]
@devjhseo This is now fixed. Please try https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/v1.6.14/
