### ISSUE TITLE
UP=true in MakeCredential F-1

### ISSUE THREAD

**Issue by kaczmarczyck** [fido-alliance/conformance-test-tools-resources#595]
## What protocol are you implementing?

- [x] CTAP 2.0
- [x] CTAP 2.1

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

## Issue description

I am reviving #516 as suggested in the [specification discussion](https://github.com/fido-alliance/fido-2-specs/issues/1119#issuecomment-737568943) on this test. The easiest way to resolve it would be to change this test to do the same check, but using `UP=false`.

Background is that authenticator's are more lenient towards platform behaviour if they accept `UP=true`. This allows backwards compatibility between CTAP2 versions as they are at the moment.

**Comment by ve7jtb** [comment]
That works for me.
