### ISSUE TITLE
Tool v1.6.14 Metadata-Stmt-1 Verify compliance of Metadata statement fields.  P-15

### ISSUE THREAD

**Issue by ve7jtb** [fido-alliance/conformance-test-tools-resources#599]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x ] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.6.14

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [ x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

Metadata-Stmt-1 Verify compliance of Metadata statement fields.  P-15

The test requires USER_VERIFY_PASSCODE_INTERNAL(0x00000004) to be present if caDesc is present.
Both USER_VERIFY_PASSCODE_INTERNAL and USER_VERIFY_PASSCODE_EXTERNAL support csDesc.
If Pin protocol is present then the tool checks USER_VERIFY_PASSCODE_INTERNAL is not present making a catch22 situation.

The test needs to be updated.  This is more a SR1.4 issue than a CTAP2.1 issue

**Comment by herrjemand** [comment]
Fixed now
