### ISSUE TITLE
conformance tool consistently crashes with BLE authenticator connection attempts

### ISSUE THREAD

**Issue by xjrosasx** [fido-alliance/conformance-test-tools-resources#602]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 Server
- [x] CTAP2.0

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [x] Server

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.5.2
v1.6.14

## What is the OS and the version are you running?

For desktop tools
- [x] OSX

## Issue description

Testing started with the CTAP2 tests on either ios or android devices. The app crashes in the middle of testing. Even if I am not performing any tests, the app still crashes. I have uninstalled apps completely and reinstalled, the BLE connection still remains and still continues to crash. 
Various logs are attached including crash report.
[crashreport.log](https://github.com/fido-alliance/conformance-test-tools-resources/files/5822484/crashreport.log)
[console.log](https://github.com/fido-alliance/conformance-test-tools-resources/files/5822485/console.log)
[tool.log](https://github.com/fido-alliance/conformance-test-tools-resources/files/5822486/tool.log)

**Comment by xjrosasx** [comment]
A colleague attempted with the same v1.5.2; and it also crashes for him. He did not run any CTAP2 tests, he installed, accepted agreement and it crashed. Just leaving it open crashed multiple times. He tested on Catalina and Big Sur.

**Comment by herrjemand** [comment]
@xjrosasx Are you running Mac OS 11?

**Comment by xjrosasx** [comment]
@herrjemand We tried with both 10.5 and 11.1 -both reproduced the issue. 2 different Macs. is this supported on Mac? or does this only work on Windows?

**Comment by herrjemand** [comment]
No, this works on mac.

I will do further investigation. This is really weird.

Yuriy Ackermann
FIDO, Identity, Standards
skype: ackermann.yuriy
github: @herrjemand <https://github.com/herrjemand>
twitter: @herrjemand <https://twitter.com/herrjemand>
medium: @herrjemand <https://medium.com/@herrjemand>
