### ISSUE TITLE
F-10 trust anchor in chain

### ISSUE THREAD

**Issue by madwizard-thomas** [fido-alliance/conformance-test-tools-resources#605]
## What protocol are you implementing?
FIDO2 Server

## What is your implementation class?

Server

## What is the version of the tool are you using?

1.6.14

## What is the OS and the version are you running?

Windows 10

## Issue description

Tool 1.6.14 under Server-ServerAuthenticatorAttestationResponse-Resp-5 there are these two tests:

- P-3 Send a valid ServerAuthenticatorAttestationResponse with FULL "packed" attestation that contains batch certificate, that is simply self referenced in the metadata, and check that server succeed
- F-10 Send ServerAuthenticatorAttestationResponse with FULL "packed" attestation, with attStmt.x5c containing full chain, and check that server returns an error

In P-3 the only certificate in the chain also exactly appears in the metadata files and is therefore a trust anchor as well. It seems logical that this test succeeds since the certificate is trusted implicitly.

In F-10 the chain contains 3 certificates, the last of which is the trust anchor itself. The trust anchor is already in the metadata so it is not necessary to include it but should it really fail? The chain, though wasteful is still valid and trustworthly. If trust anchors are not allowed to be included in the chain then why is it allowed in P-3? 

Btw, is there any official specification the conformance test is based on? It's difficult to have to figure out the specific constraints based on the tests alone sometimes, and FIDO is different or more strict than the WebAuthn spec in some cases.

**Comment by madwizard-thomas** [comment]
I found https://github.com/w3c/webauthn/pull/1509/files which explains where P-3 comes from. I'm not sure what F-10 is based on though.

**Comment by herrjemand** [comment]
@madwizard-thomas 

F-10 comes from the fact that RFC5280 prohibits dublicates in the certificate path. 

So if authenticator response contains root certificate, and metadata contains root, that will cause an error.
