### ISSUE TITLE
Impossible to identify specific tests from within the code being tested

### ISSUE THREAD

**Issue by MasterKale** [fido-alliance/conformance-test-tools-resources#609]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [x] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

Version 1.6.18 (1.6.18)

## What is the OS and the version are you running?

macOS 11.2.2

For desktop tools
- [x] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

I'm attempting to run a library through conformance testing, but there's no obvious way to know which request being handled is for which specific conformance test. This makes it difficult to summarize which tests still require code to be written before they will pass, which tests are successfully passing, which tests are masking code errors... It is a painstaking process to  go back through error logs and iterate through till I land on one that is _probably_ for the particular test I want to target for development.

It's also nearly impossible to know if a test that passes by returning an error is indeed catching the intended issue with the credential response, or if broken code throwing an exception is getting disguised as a successful test (since the conformance tool makes no prescription of error messaging content to compare with.)

Can you offer up some way for us to know which test is currently being executed? Given that HTTP is the common "API" for RP's running these tests, could you use HTTP headers to indicate which test a given request is for? Perhaps something like this:

`X-Test-Identifier: Server-ServerAuthenticatorAttestationResponse-Resp-1 F-1`

The addition of such a header would make it easy to track down and correlate code output to a given test so that we can verify that our logic is returning expected outputs.

**Comment by herrjemand** [comment]
@MasterKale X-Test-Identifier: Server-ServerAuthenticatorAttestationResponse-Resp-1 F-1

Have previously decided against that
