### ISSUE TITLE
U2F GetVersion bug.

### ISSUE THREAD

**Issue by ve7jtb** [fido-alliance/conformance-test-tools-resources#614]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [x ] U2F 1.1
- [x ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x ] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.6.29 but it also applies to earlier 1.6 versions

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

U2F CTAP1.1 or 1.2 tests for the HID transport.
In General P-1 GetVersion test you send a short APDU command..
CLA	INS	P1	P2	Le
00	03	00	00	00

The correct extended  version is:
CLA	INS	P1	P2	Le
00	03	00	00	00 00 00

While some keys will respond to both U2F HID transport requires all messages to be encoded as extended length.

https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-hid-protocol-v1.2-ps-20170411.html#u2fhid-protocol-implementation

I think the older versions of the tool were using the U2F 1.0 version of the command. 
CL	IN	P1	P2	L0	L1	L2	Le
00	03	00	00	00	00	00	00 00

In practice, I don't think any platform actually uses the GetVersion command.

**Comment by xchapron-ledger** [comment]
Hello @herrjemand , I'm still facing this on the Conformance Tool version 1.7.0.
As @ve7jtb we were not expecting to receive short encoding APDU over HID.
Is it possible to fix this?
Thanks.
