### ISSUE TITLE
U2F 1.2 dont-enforce-user-presence-and-sign(0x08) bug

### ISSUE THREAD

**Issue by ve7jtb** [fido-alliance/conformance-test-tools-resources#615]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [x ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.6.29

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [ x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

This is a new test for U2F 1.2 

Authenticate  P-4 

The logic is wrong.  It is doing the test as if 0x07 was sent.
The point of 0x08 was to get silent authentication for IoT.

It looks like a cut and paste error from the check only test.

assert.equal(APDU_STATUS_CODES.SW_CONDITIONS_NOT_SATISFIED, result.statusCode, 'For Sign with CheckOnly, for an existing credential, authenticator must return SW_CONDITIONS_NOT_SATISFIED(0x6985)! Authenticator returned: ' + APDU_STATUS_CODES[result.statusCode]);
                assert.isFalse(result.responseStruct.UP, 'Expected Authenticator to NOT to enforce User Presence!');

Sucess should be SW_NO_ERROR with an assertion that has up=0

**Comment by herrjemand** [comment]
Addressed.
