### ISSUE TITLE
Metadata Service test F-1 in v1.6.33 fails because no bad status reports for tested AAGUIDs

### ISSUE THREAD

**Issue by MasterKale** [fido-alliance/conformance-test-tools-resources#619]
## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [x] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

v1.6.33

## What is the OS and the version are you running?

For desktop tools
- [x] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

Metadata Service test F-1 tells me it succeeds when it should fail:

![Screen Shot 2021-08-21 at 10 13 23 PM](https://user-images.githubusercontent.com/5166470/130365669-3069d648-6e3b-420d-9203-31f9f4c05fea.png)

What's confusing me is that none of the AAGUIDs that are used for these tests include any with any of the expected bad statuses:

```
Getting statement for 4f086657-563a-4420-9971-d33e8e0d34f3
Status reports:
- FIDO_CERTIFIED_L1plus
Getting statement for 29b5e4a2-094e-4837-879f-a914c7a18274
Status reports:
- FIDO_CERTIFIED
Getting statement for 29b5e4a2-094e-4837-879f-a914c7a18274
Status reports:
- FIDO_CERTIFIED
Getting statement for e68036d3-0a5b-4e03-b184-ce3291dd3668
Status reports:
- SELF_ASSERTION_SUBMITTED
Getting statement for 45c9578d-8d5d-4e46-a862-b21d2e3961e9
Status reports:
- FIDO_CERTIFIED_L1plus
Getting statement for 5a30ae78-348e-4ed1-835e-16bddf96bbed
Status reports:
- FIDO_CERTIFIED_L1
Getting statement for d8e43bbc-cc1e-4309-915d-9f87e578166a
Status reports:
- FIDO_CERTIFIED_L3
Getting statement for 182a476e-0fab-4fdc-97b7-4abf8e4219c5
Status reports:
- FIDO_CERTIFIED_L3plus
```

Based on the description of the test alone it's impossible for me to understand what I need to change so that this test passes. Is `SELF_ASSERTION_SUBMITTED` now a "bad" value that should cause an error? That's the only one that stands out as a potentially new bad status to add to `USER_VERIFICATION_BYPASS`, `ATTESTATION_KEY_COMPROMISE`, `USER_KEY_REMOTE_COMPROMISE`, and `USER_KEY_PHYSICAL_COMPROMISE` that definitely came up in the MDSv2 tests.

**Comment by herrjemand** [comment]
This was resolved! Sorry for the delay.
