### ISSUE TITLE
CTAP 2.1, Tools 1.6.31 - Credential Management API test

### ISSUE THREAD

**Issue by KeySoftSK** [fido-alliance/conformance-test-tools-resources#621]
### CTAP2.1 Authenticator Tests -  Credential Management API

Hello, we have got problem with testing **credMgmt** API.
The test is trying to execute "before each" preparation. In the preparation, the tool is trying to create new credential with PIN verification, but it is not successful, because no PIN has been set before. Please see the image:

![pinError](https://user-images.githubusercontent.com/90247957/133144630-fdd9106b-849e-4d21-808c-bbd492fb3a33.PNG)

While preparation, we have received following request messages:

1. **authenticatorReset** 
2. **authenticatorGetInfo** 
3. **authenticatorClientPIN**  { 1: 2, 2: 2 }  - getKeyAgreement
4. **authenticatorClientPIN**  { 1: 2, 2: 9, .....} - getPinUvAuthTokenUsingPinWithPermissions

The test tool was freshly started, without any saved state. 
Our error is: `E/ClientPin: PIN IS NOT SET` which I think should be correct, as no previous state was set.

Please, what is the correct way to handle this? Should we preserve some state from previous tests?

Our GetInfo message:

> {1: ["FIDO_2_0", "FIDO_2_1"], 2: ["credProtect", "hmac-secret"], 3: h'AAD98202FFBD4EFF9DAF7030BE68B3CB', 4: {"rk": true, "up": true, "plat": false, "credMgmt": true, "clientPin": false, "pinUvAuthToken": false}, 5: 2048, 6: [1, 2], 7: 10, 8: 96, 9: ["ble"], 10: [{"alg": -7, "type": "public-key"}]}

Best regards
KeySoft

**Comment by nuno0529** [comment]
Tool 1.6.34 still has this issue, this test item has assumption that the authenticator has option 'alwaysUv:true`  or it will go for setting new PIN, but seems due to below line's condition is under alwaysUv:true, so the newPin won't be set
https://github.com/fido-alliance/ctap2.1-conformance-module/blob/main/js/CTAP2.js#L1088

@herrjemand could you help to check the line

**Comment by nuno0529** [comment]
Below test items has the same issue at beginning, 
- Authenticator Config
- Biometric Enrollment

**Comment by nuno0529** [comment]
> Below test items has the same issue at beginning,
> 
> * Authenticator Config
> * Biometric Enrollment

Update again on v1.6.37 that below test items still have similar issue, but above 2 test items are OK.
- Options: Resident Key, P-1 ... Got CTAP2_ERR_PIN_NOT_SET(53)
- Credential Management API, P-1 ... Got CTAP2_ERR_PUAT_REQUIRED(0x36) and before makeCred command there is a strange log 
![image](https://user-images.githubusercontent.com/6506729/146330690-d7177789-4595-4508-9e53-a253242e14c2.png)

**Comment by herrjemand** [comment]
Resolved in 1.6.38 https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/v1.6.38/

**Comment by nuno0529** [comment]
Verified below items in v1.6.39 for authenticatos with option.alwaysUv=true or false
- Options: Resident Key
- Ext: CredProtect
- Ext: CredProtect
- Credential Management API
- Authenticator Config 
- Large Blobs
