### ISSUE TITLE
FIDO Conformance Tools v1.6.34 Bug in Metadata Statement Tests

### ISSUE THREAD

**Issue by kolarzjulian** [fido-alliance/conformance-test-tools-resources#622]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [X] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [X] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
FIDO Conformance Tools v1.6.34(NEW CTAP2.0 Tests - MDS3)

## What is the OS and the version are you running?

For desktop tools
- [X] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
Hello,
I found a bug in the meta data statement tests.
As test tool version I used: FIDO Conformance Tools v1.6.34

If I run the test with a valid MetadataStatement (v3), the test case P-32 fails with: 
`TypeError: Cannot read property 'isUndefined' of undefined
    at n.eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:2498:39)`

I think it is because the field "pinUvAuthProtocols" is missing and then the check:

...
/* minPINLength - (c) If "minPINLength" present: MUST be positive integer. MUST be >= 4. If "pinUvAuthProtocols" is missing, MUST NOT be present. */
**if(getInfo.pinUvAuthProtocols.isUndefined)** { // here it fails
    assert.isUndefined(getInfo.minPINLength, `Metadata.authenticatorGetInfo.minPINLength MUST NOT be defined if pinUvAuthProtocols is undefined`);
} else {
    if(getInfo.minPINLength || getInfo.minPINLength !== undefined) {
        assert.isNumber(getInfo.minPINLength, 'Metadata.authenticatorVersion.minPINLength MUST be a number!');
        assert.isAbove(getInfo.minPINLength, 3, 'Metadata.authenticatorVersion.minPINLength MUST be a number. Minimum Pin Length is 4')
    }
}
...

AFAIK "pinUvAuthProtocols" is not a mandatory field, because the authenticator does not support clientPin.

**Comment by nuno0529** [comment]
> P-32

I can only find the test item with this tag in `ctap2.1-conformance-module`. So for ctap2.1, support pinUvAuthProtocols is mandatory.
https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#:~:text=must%20include%20an%20array%20element%20with%20the%20value%202%20in%20the%20authenticatorgetinfo%20response%E2%80%99s%20pinuvauthprotocols%20member%20(i.e.%20support%20pin%2Fuv%20auth%20protocol%20two)%20if%20it%20includes%20any%20values%20at%20all.

**Comment by kolarzjulian** [comment]
No that's not correct. The specification says:
"MUST include an array element with the value 2 in the authenticatorGetInfo response’s pinUvAuthProtocols member (i.e. support PIN/UV auth protocol two) **if it includes any values at all.**"

The important part here is ..."if it includes any values at all". So it can also be not present. And if we test with a metadata statement that does not have pinUvAuthProtocols defined, the test case crashes, because I think the test tries to call the function .isUndefined() on an object "getInfo.pinUvAuthProtocols" that is null in this case.

**Comment by nuno0529** [comment]
Oh, sorry for my misunderstanding of your case. Btw, I found it's resolved by a commit on Jul 7, 2021 and what I see in my v1.6.34  already below . So a little strange.
> if(getInfo.pinUvAuthProtocols === undefined) {
> assert.isUndefined(getInfo.minPINLength, `Metadata.authenticatorGetInfo.minPINLength MUST NOT be defined if >?pinUvAuthProtocols is undefined`);
>} else {

**Comment by kolarzjulian** [comment]
Okay, but as you can see in my post I am referring to CTAP 2.0 Protocol. And also the test description/caption in the tool states this (see screenshot):
NEW CTAP2.0 Tests - MDS3 Tests 

<img width="1040" alt="Bildschirmfoto 2021-11-11 um 17 54 33" src="https://user-images.githubusercontent.com/11873022/141337796-dbaae91e-b6dc-4aa9-8784-06f55e533309.png">

So actually we just want to test our FIDO2 (CTAP 2.0) with the new MDS3.

**Comment by nuno0529** [comment]
Actually, in my Windows' v1.6.34 or v1.6.35, there is no test category **NEW CTAP2.0 Tests - MDS3 Tests** and just the old one without this test item.
![image](https://user-images.githubusercontent.com/6506729/141405302-2d109ec7-0095-4155-9d8f-bff8585200f5.png)

But I can see this **NEW CTAP2.0 Tests - MDS3 Tests** test category on macOS' v1.6.34 or v1.6.35 and it's with old code, `if(getInfo.pinUvAuthProtocols.isUndefined)`
![image](https://user-images.githubusercontent.com/6506729/141405109-ddd81424-2046-41af-9daf-f3a26d83861c.png)

A little frustrating..
