### ISSUE TITLE
ctap2.1 Ext: Large Blob Key, P-1, the extension largeBlobKey needs option.rk=true 

### ISSUE THREAD

**Issue by nuno0529** [fido-alliance/conformance-test-tools-resources#626]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

1.6.34

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#:~:text=if%20the%20options%20field%20of%20the%20authenticatormakecredential%20request%20does%20not%20map%20rk%20to%20true%2C%20return%20ctap2_err_invalid_option.

The options is empty, below is my dump of the command

`{1: h'0169A18FF72415258EEA815F1EEE1CFF8BFB7FE9A8E65A0CE2C94A81D0F41DB9', 2: {"id": "spiritualkumquat.sz", "name": "The Example Corporation with fake domain!"}, 3: {"id": h'5371CE780B31F96A9FDEC0F96D745FC13092436BC75E56E2BE7D920862035E13', "name": "aleisha.neyman@magnificentlime.ro", "displayName": "Aleisha Neyman"}, 4: [{"alg": -7, "type": "public-key"}, {"alg": -8, "type": "public-key"}], 6: {"largeBlobKey": true}}`

**Comment by herrjemand** [comment]
Addressed in 1.6.38

**Comment by herrjemand** [comment]
Resolved in 1.6.38 https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/v1.6.38/

**Comment by nuno0529** [comment]
Thanks, I have verified it with v1.6.38.
