### ISSUE TITLE
ctap2.1 Biometric Enrollment - EnumerateRenameRemove P-1 (b) templateFriendlyName(0x02) - string, empty

### ISSUE THREAD

**Issue by nuno0529** [fido-alliance/conformance-test-tools-resources#631]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.6.34

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

Why the templateFriendlyName(0x02) must be empty? I can't find this rule in spec.
https://github.com/fido-alliance/ctap2.1-conformance-module/blob/main/tests/CTAP2/Protocol/BiometricEnrollment/21/BioEnroll-21-EnumerateRenameRemove.js#L85

**Comment by nuno0529** [comment]
I remember there was some compatibility issue to use empty friendly name on chrome80's bioEnroll setttings around Nov-2019.

**Comment by herrjemand** [comment]
Fixed in 1.6.38

**Comment by herrjemand** [comment]
Resolved in 1.6.38 https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/v1.6.38/

**Comment by nuno0529** [comment]
Thanks, I have verified it with v1.6.38
