### ISSUE TITLE
ctap2.1 Options: Enterprise Attestation - some errors in test code

### ISSUE THREAD

**Issue by nuno0529** [fido-alliance/conformance-test-tools-resources#632]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.6.34

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
P-2
1. The epAtt is the parameter of makeCred response, not under attStmt.
https://github.com/fido-alliance/ctap2.1-conformance-module/blob/main/tests/CTAP2/Protocol/Options/EntepriseAttestation.js#L137
   - https://github.com/fido-alliance/ctap2.1-conformance-module/blob/main/js/CTAP2.js#L132
1. Where is the private_key of EPBatchCertificatePEM for passing this test item
https://github.com/fido-alliance/ctap2.1-conformance-module/blob/main/tests/CTAP2/Protocol/Options/EntepriseAttestation.js#L145
    - I found this is under https://github.com/fido-alliance/ctap2.1-conformance-module/blob/main/pki/EPBatchCertificate.key, -~~but how could authenticator vendors without this link's access right to get this?~~
Sorry, I see this is under https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs/FIDO2/Security-Key

P-3
1. Need remove `response.` of below line
https://github.com/fido-alliance/ctap2.1-conformance-module/blob/main/tests/CTAP2/Protocol/Options/EntepriseAttestation.js#L181

**Comment by nuno0529** [comment]
Update
- If the authenticator's option.alwaysUv = false
  - v1.6.35 failed at beginning due to clientPin is not set error.
  - v1.6.36 failed due to option.ep is not enabled due to authenticatorConfig_EnableEnterpriseAttestation() is not called.
- Else
   - remain 1 error in P-2 **AssertionError: attStmt is missing epAtt field!** but epAtt is under makeCred not attStmt

**Comment by nuno0529** [comment]
>   * remain 1 error in P-2 **AssertionError: attStmt is missing epAtt field!** but epAtt is under makeCred not attStmt

In v1.6.37, only remain this issue with using authenticatorss getInfo.option.alwaysUv = false

**Comment by herrjemand** [comment]
Addressed

**Comment by nuno0529** [comment]
Test with v1.6.38, but P-2 still failed and I think below 2 lines need to modify too.
https://github.com/fido-alliance/ctap2.1-conformance-module/blob/main/tests/CTAP2/Protocol/Options/EntepriseAttestation.js#L137-L138

Besides, F-6 also has similar parts need to update
https://github.com/fido-alliance/ctap2.1-conformance-module/blob/main/tests/CTAP2/Protocol/Options/EntepriseAttestation.js#L312-L315

**Comment by herrjemand** [comment]
Resolved in 1.6.39 https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/v1.6.39/

**Comment by nuno0529** [comment]
v1.6.41 still has the issue in P-2, please help to remove the parts to use `attStmt.epAtt` in P-2/F-6 as your previous modification, https://github.com/fido-alliance/ctap2.1-conformance-module/commit/02d1d89fe3f24e6100f8c5357f67b48d8f12b432#diff-22bd3cb516e148a24c13183ef582189c49a7fdce224141747314eb3f6067423fR139

**Comment by nuno0529** [comment]
I have verified this issue with v1.6.42, thanks.
