### ISSUE TITLE
FIDO2 Server MDS3 Metadata Service Tests - CRL expired for the intermediate cert in the metadata blob 

### ISSUE THREAD

**Issue by vs-nnl** [fido-alliance/conformance-test-tools-resources#633]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ x] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [x ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.6.35

## What is the OS and the version are you running?
MacOS 11.6
For desktop tools
- [ x] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
Intermediate certificate in the metadata blob for the MDS3 - Metadata Service Tests points to an expired CRL.

Issuer | CN = FAKE Root FAKE,OU = FAKE Metadata 3 BLOB ROOT FAKE,O = FIDO Alliance,C = US
-- | --
Subject | CN = FAKE CA-1 FAKE,OU = FAKE Metadata 3 BLOB INTERMEDIATE FAKE,O = FIDO Alliance,C = US
Valid From | 1 Feb 2017, midnight
Valid To | 31 Jan 2040, 11:59 p.m.
Serial Number | 04:1D:42:7E:9D:8B:C5:91:7E:C2:E9:F5:FC:1A:93 (21362645556943795005405763397753491)

The above cert contains:
```
X509v3 CRL Distribution Points: 

                Full Name:
                  URI:https://mds3.certinfra.fidoalliance.org/crl/MDSROOT.crl
```

MDSROOT.crl:

```
$ openssl crl -in MDSROOT.crl -inform DER -text -noout
Certificate Revocation List (CRL):
        Version 2 (0x1)
    Signature Algorithm: ecdsa-with-SHA384
        Issuer: /C=US/O=FIDO Alliance/OU=FAKE Metadata 3 BLOB ROOT FAKE/CN=FAKE Root FAKE
        Last Update: Feb  1 00:00:00 2018 GMT
        Next Update: Feb  1 00:00:00 2020 GMT <== CRL has expired
        CRL extensions:
            X509v3 CRL Number:
                1
            X509v3 Authority Key Identifier:
                keyid:06:71:F7:82:B3:46:3C:0F:E9:61:E9:4E:41:DB:14:AB:47:BE:1E:1D
```
Intermediate cert and MDSROOT.crl attached.

[intermediate.txt](https://github.com/fido-alliance/conformance-test-tools-resources/files/7591926/intermediate.txt)
[MDSROOT.crl.txt](https://github.com/fido-alliance/conformance-test-tools-resources/files/7591927/MDSROOT.crl.txt)

**Comment by purrema1** [comment]
Using v1.6.42: still an issue: 'Could not determine revocation status' due to expired CRLs:

https://mds3.certinfra.fidoalliance.org/crl/MDSCA-1.crl   Next Update: Feb  1 00:00:00 2022 GMT <-- expired
https://mds3.certinfra.fidoalliance.org/crl/MDSROOT.crl   Next Update: Feb  1 00:00:00 2020 GMT <-- expired

Furthermore, when bypassing the revocation check, the retrieved metadata statement is no a valid mdsv3 one,.
Eg: 'Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator 74a2e35c-7f5b-4537-a212-8b1e208992ca' contains:
...
userVerificationDetails:
**userVerification**: "none"
... 
which is not mdsv3 conform! It needs to be:
**userVerificationMethod**, instead

**Comment by gsprdev** [comment]
purrema1 is correct, this is an ongoing issue.

From an example cert under evaluation, I see
```
CRLDistributionPoints [
  [DistributionPoint:
     [URIName: https://mds3.certinfra.fidoalliance.org/crl/MDSCA-1.crl]
]]
```
in the chain, tracing up to
```
CRLDistributionPoints [
  [DistributionPoint:
     [URIName: https://mds3.certinfra.fidoalliance.org/crl/MDSROOT.crl]
]]
```
at the root.

The following shows a fresh download and evaluation of these intermediate and root CRLs.
```
╭─gspreder@ACCLT2257.accertify.com /tmp/mds
╰─➤  curl https://mds3.certinfra.fidoalliance.org/crl/MDSCA-1.crl -O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   496  100   496    0     0   1591      0 --:--:-- --:--:-- --:--:--  1636

╭─gspreder@ACCLT2257.accertify.com /tmp/mds
╰─➤  openssl crl -in ./MDSCA-1.crl -inform DER -text -noout
Certificate Revocation List (CRL):
        Version 2 (0x1)
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: /C=US/O=FIDO Alliance/OU=FAKE Metadata 3 BLOB INTERMEDIATE FAKE/CN=FAKE CA-1 FAKE
        Last Update: Feb  1 00:00:00 2018 GMT
        Next Update: Feb  1 00:00:00 2022 GMT
        CRL extensions:
            X509v3 CRL Number:
                1
            X509v3 Authority Key Identifier:
                keyid:A3:84:A7:A4:64:A2:89:3C:0A:BF:17:9E:A2:0D:F0:12:1A:A6:D7:CB

Revoked Certificates:
    Serial Number: 042D2F42CCBB713494CE1531D7895F
        Revocation Date: Apr 13 00:00:00 2016 GMT
        CRL entry extensions:
            X509v3 CRL Reason Code:
                Unspecified
    Serial Number: 04C5E8F3BA4A5C95A5E714B1AFC431
        Revocation Date: Mar 25 00:00:00 2017 GMT
        CRL entry extensions:
            X509v3 CRL Reason Code:
                Unspecified
    Serial Number: 04AF5DE8B97F0A35FDD53ABE0ECD01
        Revocation Date: Mar  1 00:00:00 2016 GMT
        CRL entry extensions:
            X509v3 CRL Reason Code:
                Unspecified
    Serial Number: 04806749DE307BBD5175A26D73F5F3
        Revocation Date: Mar 25 00:00:00 2018 GMT
        CRL entry extensions:
            X509v3 CRL Reason Code:
                Unspecified
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:20:0e:0b:6c:84:b7:f9:ff:cd:a6:1d:c3:a0:97:64:
         ec:52:2c:c7:b2:32:c2:b2:59:90:54:37:52:3d:ca:25:4b:c5:
         02:21:00:da:e4:c4:a3:41:b5:f5:bf:c3:24:08:fa:73:c5:ba:
         c1:6f:52:39:d7:46:92:4e:e6:41:d1:15:2e:c0:f9:ce:63

╭─gspreder@ACCLT2257.accertify.com /tmp/mds
╰─➤  curl https://mds3.certinfra.fidoalliance.org/crl/MDSROOT.crl -O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   475  100   475    0     0   1511      0 --:--:-- --:--:-- --:--:--  1552

╭─gspreder@ACCLT2257.accertify.com /tmp/mds
╰─➤  openssl crl -in ./MDSROOT.crl -inform DER -text -noout
Certificate Revocation List (CRL):
        Version 2 (0x1)
    Signature Algorithm: ecdsa-with-SHA384
        Issuer: /C=US/O=FIDO Alliance/OU=FAKE Metadata 3 BLOB ROOT FAKE/CN=FAKE Root FAKE
        Last Update: Feb  1 00:00:00 2018 GMT
        Next Update: Feb  1 00:00:00 2020 GMT
        CRL extensions:
            X509v3 CRL Number:
                1
            X509v3 Authority Key Identifier:
                keyid:06:71:F7:82:B3:46:3C:0F:E9:61:E9:4E:41:DB:14:AB:47:BE:1E:1D

Revoked Certificates:
    Serial Number: 0426587D66EF02D0A20A20E4CE554136
        Revocation Date: Mar  1 00:00:00 2014 GMT
        CRL entry extensions:
            X509v3 CRL Reason Code:
                Unspecified
    Serial Number: 3075BAE2EBFAD860F780E4DAD8EE4E5D
        Revocation Date: Apr 13 00:00:00 2014 GMT
        CRL entry extensions:
            X509v3 CRL Reason Code:
                Unspecified
    Serial Number: 59AA0A85691342EBA14D9C97E4F5B782
        Revocation Date: Mar 25 00:00:00 2015 GMT
        CRL entry extensions:
            X509v3 CRL Reason Code:
                Unspecified
    Signature Algorithm: ecdsa-with-SHA384
         30:65:02:30:72:be:b5:6f:25:64:b6:77:a8:cc:70:55:c3:84:
         81:98:97:de:81:1a:33:b5:ad:7a:27:9a:a0:a8:3e:47:9e:1c:
         0b:3b:20:4b:f1:a6:80:87:e7:fd:dc:d6:0c:a6:21:9a:02:31:
         00:aa:fa:fd:2f:1a:b1:3b:05:f7:2a:28:9f:a8:6f:ce:1f:aa:
         ce:c7:a5:b5:ab:e4:af:b8:ae:ec:15:6c:d9:d3:06:e9:64:ad:
         af:d3:fd:81:1b:e1:93:65:02:c5:b9:3a:5a
```

I understand that some *intermediate* certs (and possibly CRLs) are intentionally invalidated to confirm that we're checking for these, so I understand that the expiration of the intermediate CRL is not necessarily unintentional. The expiration of the *ROOT*, however, seems like an oversight.

I have checked several certified OSS implementations, and they all have workarounds of various forms to circumvent this or similar infrastructure issues. We shouldn't have to cheat the test.

**Comment by herrjemand** [comment]
Resolved
