### ISSUE TITLE
ctap2.1 Options: Resident Key. under option.uv=true, makeCred command fails.

### ISSUE THREAD

**Issue by nuno0529** [fido-alliance/conformance-test-tools-resources#637]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.6.37

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
The 1st parameter `makeCredStruct.clientDataHash` of this line is undefined.
https://github.com/fido-alliance/ctap2.1-conformance-module/blob/90100e1e2b602457df67b42e43ac9312e2800abb/tests/CTAP2/Protocol/Options/ResidentKey.js#L245

**Comment by nuno0529** [comment]
This issue only happens with authenticator's getInfo.option.uv = true case.

**Comment by herrjemand** [comment]
Addressed in 1.6.38

**Comment by herrjemand** [comment]
Resolved in 1.6.38 https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/v1.6.38/

**Comment by nuno0529** [comment]
This issue is gone in v1.6.38, but a following issue happens, #643
