### ISSUE TITLE
ctap2.1 Options: Resident Key. P-3 under option.uv=true, makeCred command fails

### ISSUE THREAD

**Issue by nuno0529** [fido-alliance/conformance-test-tools-resources#643]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.6.38

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
After the fix of #637, with https://github.com/fido-alliance/ctap2.1-conformance-module/commit/cc1f4191a734222ce58bff0e135ecd185890cb3f#diff-1ceeef653d813722f88baf4ea2a380bc21b4f83168d1ebdc613e408771cc16b0R245

I think below line also need to copy below line
- https://github.com/fido-alliance/ctap2.1-conformance-module/blob/main/tests/CTAP2/Protocol/Options/ResidentKey.js#L240
 
Or the P-3 test item gets below error
```
AssertionError: User with user.id "22f6a1acdee79afaa70a6e41fd6c836220894425d3fbee33a44b1382ba8a4520" was never registered!: expected undefined to not equal undefined
    at eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5654:32)
```

**Comment by herrjemand** [comment]
Fixed in the next version

**Comment by herrjemand** [comment]
Resolved in 1.6.39 https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/v1.6.39/

**Comment by nuno0529** [comment]
Your recent change makes P-2 items failed for both option.uv = true/false case.
https://github.com/fido-alliance/ctap2.1-conformance-module/commit/605411e6f5d01516b749baccb63331a9d2794c49#diff-1ceeef653d813722f88baf4ea2a380bc21b4f83168d1ebdc613e408771cc16b0L192

My previous comment is for P-3 that need to copy below line to `else` part for option.uv=true case
![image](https://user-images.githubusercontent.com/6506729/150275462-8910fdcb-55a1-441f-91fd-76c7020a8e15.png)

**Comment by nuno0529** [comment]
v1.6.41 has resolved P-2 issue. And for the P-3 issue, I filed new issue to #652
