### ISSUE TITLE
ctap2.1 ClientPin protocol 2/Authr-ClientPin2-Policy, F-1/F-2/F-3 no reset before setNewPin

### ISSUE THREAD

**Issue by nuno0529** [fido-alliance/conformance-test-tools-resources#645]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.6.38

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

So F-1 will get error `Expected authenticator to fail with CTAP2_ERR_PIN_POLICY_VIOLATION(55). Got CTAP2_ERR_PIN_AUTH_INVALID(51): expected 51 to equal 55` due to the PIN is already set.
And F-2/F-3 is okay result, but it's due to the error code is relaxed by #627 that only check `assert.notStrictEqual(ctap2Response.statusCode,....`

**Comment by herrjemand** [comment]
Fixed in the next version

**Comment by herrjemand** [comment]
Resolved in https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/EXPERIMENTAL/v1.6.39/

**Comment by nuno0529** [comment]
Thanks, I have verified this with v1.6.39.
