### ISSUE TITLE
Testsuite 'UAF1.1 Server - MDS3 Tests' not available

### ISSUE THREAD

**Issue by purrema1** [fido-alliance/conformance-test-tools-resources#646]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [X] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [X] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

1.6.38

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [X] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

For FIDO2 server there are 2 test suites selectable:
1) FIDO2 Server (LEGACY MDS2. DEPRECATED SEPT 2021) Tests
2) NEW: FIDO2 Server - MDS3 (EXPERIMENTAL) Tests

For UAF1.1 there is only one suite (already deprecated!):
1) UAF (LEGACY MDS2. DEPRECATED SEPT 2021) 1.1 Tests

The UAF1.1 MDS3 module: 'uaf-v1.1-conformance-module' is available, but hidden:
"hide": true (in manifesto.json).

Is this on purpose, or a mistake?
Will there be an own module for 'UAF11 Server - MDS3' tests?

**Comment by herrjemand** [comment]
Hey @purrema1 in long term we are planning to add MDS3 UAF1.1 support.

**Comment by pheimfido** [comment]
The newest build, v1.7.0, includes updates and alignment with UAF v1.2 and MDS3 scheme.
