### ISSUE TITLE
CTAPHID_CANCEL test fail

### ISSUE THREAD

**Issue by laughingbro** [fido-alliance/conformance-test-tools-resources#656]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] CTAP2.0
- [x] CTAP2.1
- [x] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

v1.6.41
## What is the OS and the version are you running?

For desktop tools
- [x] Windows

## Issue description
P-10 Send a valid MakeCredential request, and check that authenticator returns CTAPHID_KEEPALIVE(0x3B) while its waiting for user action. Send CTAPHID_CANCEL(0x11) and check that authenticator responds with CTAPHID_CBOR(0x90) with error code CTAP2_ERR_KEEPALIVE_CANCEL(0x2D). Send another CTAPHID_CANCEL(0x11) and check that authenticator does not respond with anything.

The testing result:
![tool](https://user-images.githubusercontent.com/90955290/154433708-d8a9161d-5531-4b01-97ce-6aaf02268a5e.png)

But I capture the usb transfering command, can't find any error.
![bushound](https://user-images.githubusercontent.com/90955290/154433941-56ef4dd4-3bee-4387-9382-8e5830546f8f.png)

The respond is CTAPHID_CBOR(0x90) with CTAP2_ERR_KEEPALIVE_CANCEL(0x2D), can't find undefined(0x00).

**Comment by nuno0529** [comment]
This should be the same issue as #612. Current test code has a special behavior here that it expects the `CTAP2_ERR_KEEPALIVE_CANCEL(0x2D)` error will just be arrived 50ms later after sending out the 0x91 cancel command.
