### ISSUE TITLE
v1.6.42 CTAP2.1 Authenticator - MinPinLength extension fail

### ISSUE THREAD

**Issue by laughingbro** [fido-alliance/conformance-test-tools-resources#659]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.6.42

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
The testing result:
AssertionError: Authenticator did not return any extensions data, despite claiming it's support of the "minPinLength" extension!: expected undefined to not equal undefined

I can't find the specified rpId have been configed. So authenticator may return any extensions data?
![1 6 38](https://user-images.githubusercontent.com/90955290/155446639-bed841be-0a07-454c-a1a5-90833512ecb7.png)

**Comment by nuno0529** [comment]
I think there should a P-0 item to use authenticatorConfig (0x0D)-subcommand [setMinPINLength](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#setMinPINLength) with parameter `minPinLengthRPIDs(0x02)` first.

**Comment by nuno0529** [comment]
Besides, I see the test item will do below check
`assert.isAbove(extensionsStruct['minPinLength'], 4, 'minPinLength must be at least four chars long!');`

But I don't see there is any pre-set command for larger newMinPINLength value first.
