### ISSUE TITLE
FIDO2 Server - MDS3: Invalid property "userVerification" in server metadata files

### ISSUE THREAD

**Issue by purrema1** [fido-alliance/conformance-test-tools-resources#661]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [x] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

v1.6.42

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

Multiple server metadata files contain invalid property "userVerification". To be mdsv3 aligned it should be "userVerificationMethod":

Virtual FIDO2 EdDSA25519 SHA512 Conformance Testing CTAP2 Authenticator.json
Virtual RSA PCKS1.5 SHA1 FIDO2 Conformance Testing CTAP2 Authenticator.json
Virtual RSA PCKS1.5 SHA256 FIDO2 Conformance Testing CTAP2 Authenticator.json
Virtual RSA PCKS1.5 SHA384 FIDO2 Conformance Testing CTAP2 Authenticator.json
Virtual RSA PCKS1.5 SHA512 FIDO2 Conformance Testing CTAP2 Authenticator.json
Virtual RSA PKCS 1.5 SHA1 FIDO2 Conformance Testing CTAP2 Authenticator with TPM Attestation.json
Virtual RSA PKCS 1.5 SHA256 FIDO2 Conformance Testing CTAP2 Authenticator with SafetyNet attestation.json
Virtual RSA PKCS 1.5 SHA256 FIDO2 Conformance Testing CTAP2 Authenticator with TPM Attestation.json
Virtual RSAPSS SHA256 FIDO2 Conformance Testing CTAP2 Authenticator.json
Virtual RSAPSS SHA384 FIDO2 Conformance Testing CTAP2 Authenticator.json
Virtual RSAPSS SHA512 FIDO2 Conformance Testing CTAP2 Authenticator.json
Virtual Secp256K1 FIDO2 Conformance Testing CTAP2 Authenticator.json
Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator with Android Key Attestation.json
Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator with Apple Anonymous Attestation.json
Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator with Self Batch Referencing.json
Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator with Self(surrogate) attestation.json
Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator with supported extensions.json
Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator.json
Virtual Secp256R1 Multiple Root Certificates FIDO2 Conformance Testing CTAP2 Authenticator.json
Virtual Secp384r1 SHA384 FIDO2 Conformance Testing CTAP2 Authenticator.json
Virtual Secp521r1 SHA512 FIDO2 Conformance Testing CTAP2 Authenticator.json

**Comment by herrjemand** [comment]
Addressed in 1.6.46

**Comment by Spomky** [comment]
Excellent @herrjemand.
You rock!
