### ISSUE TITLE
Invalid data : Not a SEQUENCE ASN/DER structure

### ISSUE THREAD

**Issue by JisungPark0122** [fido-alliance/conformance-test-tools-resources#663]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ x] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x ] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.6.42

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
Auth-MakeCred-Resp-2 Test "packed" attestation
Alg : RSASSA PKCS1 v1.5 SHA256
Error : Invalid data : Not a SEQUENCE ASN/DER structure

It seem that tools always check ASN format of signature while the signature is not ASN.1 wrapped.
https://www.w3.org/TR/webauthn/#:~:text=the%20hash%20function.-,The%20signature%20is%20not%20ASN.1%20wrapped.,-For%20COSEAlgorithmIdentifier%20%2D37

![Not_a_SEQUENCE_ASN](https://user-images.githubusercontent.com/97420250/158300079-469bd57f-ad78-4039-aa1f-f64abb9e8b44.png)

**Comment by herrjemand** [comment]
yes. RSA signature must be x509 encoded
