### ISSUE TITLE
Authenticator Tests,Error: Timeout of 60000ms exceeded.   The test cannot be completed within the limited time.

### ISSUE THREAD

**Issue by chentufeiyang54** [fido-alliance/conformance-test-tools-resources#666]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [✔] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ✔] CTAP2.0
- [✔ ] CTAP2.1
- [ ] UAF 1.1
- [ ✔] U2F 1.1
- [ ✔] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [✔ ] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.5.2 and v1.6.42 

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [✔] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
     v1.5.2 and v1.6.42 fido tools also have same question.
     some test needs to be completed within a limited time. for example.For example, see the figure below.It need 60 seconds to complete the test. I found someproblem in the Bluetooth packet captureI .tools(master) will send the next command after 2.4 seconds when had receive slave responese.In the 60s test, the useless time interval is 50s. So it can not finish the test in 60s.
    U2F command test also have the  same question . 
    But I  use the same device test in v1.3.4 fido tool,it not have this question. when receiving commands ,tools(master) will send the next command after 0.12s when had receive slave responese.
 

![图片](https://user-images.githubusercontent.com/101798494/158787414-e2793acc-05d4-4992-9b4e-922d59463d45.png)
![图片](https://user-images.githubusercontent.com/101798494/158788201-cfda6544-2cc2-4803-9f16-ca0fe7d3522e.png)
![图片](https://user-images.githubusercontent.com/101798494/158794492-9c8c8db7-ab46-45be-84ae-cbae3cc59868.png)

the same device test in v1.3.4 fido tool,only need 120ms，see the figure below.
![图片](https://user-images.githubusercontent.com/101798494/158797993-eeacfba9-6cfa-4536-84af-445b87b3c948.png)

**Comment by herrjemand** [comment]
Resolved in 1.6.46

**Comment by chentufeiyang54** [comment]
您好，你的邮件我已收到，谢谢。
