### ISSUE TITLE
Suggest ctap2.1 to add hmacSecret test with pin_v2

### ISSUE THREAD

**Issue by nuno0529** [fido-alliance/conformance-test-tools-resources#667]
As of now, the current hmacSecret.js only applies the pin_v1 test by default. I think it's necessary to add the pin_v2 test because on most platforms that use this feature is Windows and Windows will use pin_v2 if it's available in the authenticator.

**Comment by nuno0529** [comment]
Besides, hmcSecret test items now doesn't support authenticators with options.alwaysUv=true well, P-2 will be failed.

**Comment by herrjemand** [comment]
This one is now addressed

**Comment by herrjemand** [comment]
https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.7.14/
