### ISSUE TITLE
Missing common IDL in FIDO2 sever conformance API doc

### ISSUE THREAD

**Issue by MihirLuthra** [fido-alliance/conformance-test-tools-resources#670]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [X] FIDO2 Server

## Issue description

The [conformance test document](https://github.com/fido-alliance/conformance-test-tools-resources/blob/master/docs/FIDO2/Server/Conformance-Test-API.md#serverauthenticatorattestationresponse) mentions that `ServerAuthenticatorResponse` should be in the common IDL. But it is not described there.

> Note that the ServerAuthenticatorAttestationResponse extends the generic ServerAuthenticatorResponse, which is described in the Common section below

The only field that this common IDL should have is `clientDataJSON`. It is already described in the inheriting models. So, I think either the above line should be modified or a common IDL should be added.

**Comment by herrjemand** [comment]
@MihirLuthra Here is a full description of the conformance api https://github.com/fido-alliance/conformance-test-tools-resources/blob/master/docs/FIDO2/Server/Conformance-Test-API.md

**Comment by MihirLuthra** [comment]
@herrjemand I already attached that link in my issue description. The conformance API claims to specify a model named "ServerAuthenticatorResponse" in its [common section](https://github.com/fido-alliance/conformance-test-tools-
resources/blob/master/docs/FIDO2/Server/Conformance-Test-API.md#common) but doesn't do that. It's not really a big problem but thought I should mention.

It's possible that I missed some point (sorry if that's the case) but I would request you to re-read the issue description once.

**Comment by herrjemand** [comment]
ServerAuthenticatorResponse is a placeholder object.
