### ISSUE TITLE
UAF - Facet ID with capital letters in bundleID does not pass conformance tool.

### ISSUE THREAD

**Issue by wir349** [fido-alliance/conformance-test-tools-resources#671]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] UAF 1.1

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] UAF Client-ASM-Authenticator combo

## What is the version of the tool are you using?

1.6.2.

## What is the OS and the version are you running?

iOS 15

## Issue description

When using the FIDO Conformance Tool for Client + Authenticator combo on iOS, the FacetID should be in the format "ios:bundle-id:<Bundle ID>" of application. If the bundle id contains capital letters, then I get the error:

"Invalid facetID format! For Android it MUST be android:apk-key-hash:<sha1_hash-of-apk-signing-cert> and for iOS ios:bundle-id:<ios-bundle-id-of-app>!"

A bundle ID with capital letters is a valid bundleID according to Apple and should also accepted by the conformance tool.

**Comment by herrjemand** [comment]
This issue is fixed in the core, but will require time for the 1.6.3 to be finished. 

In the meantime I suggest temporarily changing your bundleid.
