### ISSUE TITLE
UAF - Trusted Facets Api Response doesn't include version 1.1 support

### ISSUE THREAD

**Issue by wir349** [fido-alliance/conformance-test-tools-resources#672]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] UAF 1.1

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] UAF Client-ASM-Authenticator combo

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

1.6.2

## What is the OS and the version are you running?

For UAF mobile tools
- [x] iOS

I have the UAF iOS conformance tool set to version 1.1 and when I run tests which retrieve trusted facets from an external URL, they fail. After looking into the issue it seems like the URL doesn't support version 1.1 and I only get a response for version 1.0

A sample URL like the following:
https://appid.certinfra.fidoalliance.org/execute/3tvH7KbelDuFiMF22YsQZ1cW_hDrdRTYuDPjC0n8

Returns the below result. 

{
  "trustedFacets": [
    {
      "version": {
        "major": 1,
        "minor": 0
      },
      "ids": [
        "ios:bundle-id:com.accertify.fidouafclient1",
        "https://fidoalliance.nz/"
      ]
    }
  ]
}

**Comment by herrjemand** [comment]
Version of the trusted facet list must be set to 1.0.

The version of the UAF spec is not expressed in the TFL. It's independent versioning from the UAF
