### ISSUE TITLE
The before-hook has thrown an error

### ISSUE THREAD

**Issue by drwjf** [fido-alliance/conformance-test-tools-resources#674]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [X] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [X] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

V1.6.2

## What is the OS and the version are you running?

iOS 14.7

For desktop tools
- [ ] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [X] iOS
- [ ] Android

## Issue description

- Run test "Protocol-Dereg-Req-4 Test client correctly processing AppID and Facets" in Deregistration

- Error happened at F-10, it is "Send DeregistrationRequest UAF message for the given metadata statement, with "header.appID" set to the "https" URI that leads to the trusted facets list, where trustedFacets SEQUENCE contains TrustedFacet with "ids" key of type NOT SEQUENCE, wait for the response, and check that API returns UNTRUSTED_FACET_ID(0x07) error"

- The conformance test tool reports "Error: The before-hook has thrown an error. Please check that you are passing positive tests in request test cases, as it is the most likely cause of hook's failure.  the error message is : 255" 

## More information

- After check log, no unexpected 255 error code return to the conformance test. there is only 1 response include 255 for request: `[{"header":{"op":"Dereg","upv":{"major":1,"minor":1},"appID":"","exts":[{"id":"unknown-id","data":"","fail_if_unknown":true}]},"authenticators":[{"aaid":"0082#0001","keyID":"grB8JKSXAxIpxvIBF6ICtFqgbzqLp3tXC4eRxJjsSKE"}]}]`

- Unlike other passed `P-` test cases with a `v` prefix, The prefixes of `P-` test cases in the Protocol-Dereg-Req-4 are `.` The screenshot attached for reference.

![IMG_0391](https://user-images.githubusercontent.com/6302873/171520152-7f1af0ef-f909-46df-8725-32ea1cf3430f.PNG)

**Comment by Brad7711** [comment]
@herrjemand We encountered the same problem many times (before-hook error code 255) on the same platform and app version, which occurs randomly in the test cases (could be anywhere). Could you provide any information for this? Thanks.
