### ISSUE TITLE
`residentKey` (webauthn-2) parameter is not understood

### ISSUE THREAD

**Issue by Spomky** [fido-alliance/conformance-test-tools-resources#676]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [x] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

v1.7.0

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [ ] Windows
- [x] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

With the test `P-1 Get ServerPublicKeyCredentialCreationOptionsResponse`, the `authenticatorSelection` parameter shall be equal to `{"requireResidentKey":false,"userVerification":"preferred"}`.
However, we started implementing the `residentKey` parameter defined in [the API level 2](https://www.w3.org/TR/webauthn-2/#dictionary-authenticatorSelection) (and 3).

This test is too rigid and does not allow the additional parameter causing an exception:

> AssertionError: Response.authenticatorSelection MUST be set to the requested authenticatorSelection! Expected "{"requireResidentKey":false,"userVerification":"preferred","residentKey":"preferred"}" to equal "{"requireResidentKey":false,"userVerification":"preferred"}": expected { Object (requireResidentKey, userVerification, ...) } to deeply equal { Object (requireResidentKey, userVerification) }
    at n.eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:4523:16)

Is it possible to relax the test in a way that level 2/3 options are understood or unknown parameters are ignored?

Many thanks.
Regards.

**Comment by herrjemand** [comment]
You must return only requested options

**Comment by NankoPrinzhorn** [comment]
Hi,

Is there an update on this issue? 

An TODO has been set by @Spomky in https://github.com/web-auth/webauthn-lib/commit/7ff08aadeeda607b23e5f947cbacfed388d5e3a7

But this issues is closed and yet the TODO is referring to it

Many thanks :)
