### ISSUE TITLE
Invalid MDS3 metadata statements from test MDS3 server https://mds3.certinfra.fidoalliance.org/

### ISSUE THREAD

**Issue by sbweeden** [fido-alliance/conformance-test-tools-resources#679]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [X ] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [ X] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.7.2

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

I registered my server endpoint for the MDS3 test server, and received a set of MDS3 URLs, which included this one:

https://mds3.certinfra.fidoalliance.org/execute/c9b504020a263add078e0f9d3de62a5b3b542e77b74ebc774dd9e608a4dd92e6

I retrieved the blob from that URL, decoded the JWT, and noticed that there are many entries which have a structure like:
```
   "userVerificationDetails": [
      [
        {
          "userVerification": "none"
        }
      ],
      [
        {
          "userVerificationMethod": "presence_internal"
        }
      ],
	...
```

After looking into the [VerificationMethodDescriptor  defined in the MDS3 spec](https://github.com/fido-alliance/mds-specs/blob/master/fido-metadata-statement.bs#L276) I don't believe the use of `"userVerification": "none"` above is valid. I believe that should be `"userVerificationMethod": "none"`.

**Comment by herrjemand** [comment]
@sbweeden Fixed. Please follow to https://mds3.certinfra.fidoalliance.org/ and regenerate your payloads
