### ISSUE TITLE
v1.7.2 U2F Authenticator - If USBHID_INIT is blocked during authentication, the tool judges Sequence out of order.

### ISSUE THREAD

**Issue by tanepod** [fido-alliance/conformance-test-tools-resources#682]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [X] U2F 1.1
- [X] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [X] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.7.2

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [X] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

Sequence out of order occurred on F-1 because test F-1 was initiated before the ADPU message for test P-4 was completed and  USBHID_INIT on F-1 was blocked until P-4's completion.

```
F-1 Send an APDU Authenticate command with a data buffer that is missing keyHandle(so 66 bytes long), wait for the respone, and check that response status code is SW_WRONG_DATA.‣
Error: Sequence out of order!
    at processResponseBuffers (eval at compileCode (js/sandbox.js:25:26), <anonymous>:240:19)
    at eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:266:20)

```

![v1 7 2-u2f_f-1_test_start_issue](https://user-images.githubusercontent.com/44187392/183565122-216ec692-42ea-4d33-a53f-946815107cab.png)

The result of transaction analysis using the USB protocol analyzer are as follows.

![usb-analyzer_U2FHID_INIT_at_F-1](https://user-images.githubusercontent.com/44187392/183571483-8063a383-6465-4ed8-a238-9757da0d0bb9.png)

F-1 U2F_AUTHENTIACTE  with dontEnforceUP was send from 0:16.041 sec to 0:16.043 sec.
The tool tried to receive a response  starting at 0:15.675 sec, completed at 0:16.163 sec.

On the other hand, the tool tried to send USBHID_INIT on F-1 at 0:16.067 sec.
HSBHID_INIT was blocked until 0:16.165 sec (USB NAK was returned), and then a new CID was assigned at 0:16.165.
However, the tool does not allow this delay.

**Comment by herrjemand** [comment]
Addressed in 1.7.3

**Comment by tanepod** [comment]
Thank you very much!
However, from v1.7.4 to v1.7.9 the tool hangs or throws following errors for all of Test Authentication".
(Exclude v1.7.3 for windows as it was missing.)
```
Error: the object {
  "error": "IPC Timeout"
} was thrown, throw an Error :)

```

**Comment by tanepod** [comment]
The error also occurred on MacOS.
