### ISSUE TITLE
pinUvAuthProtocol is forced to 2 in CM tests

### ISSUE THREAD

**Issue by dangfan** [fido-alliance/conformance-test-tools-resources#684]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

1.7.2

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

When testing Credential Management API in the tool, it always sets `pinUvAuthProtocol` as 2. However, my authenticator reports that it only supports protocol 1. By examining the source code from the Inspector, I found that the function `getTestPinUVAuthTokenWithPermissions` does this behavior by defining a constant `pinUvAuthProtocol`.

**Comment by herrjemand** [comment]
getTestPinUVAuthTokenWithPermissions is only available in pinProtocol2

**Comment by nuno0529** [comment]
> getTestPinUVAuthTokenWithPermissions is only available in pinProtocol2

I don't see this behavior in spec. 
But ctap2.1 compliant authenticators must support pinUvAuthProtocol v2 (if it supposes clientPin) and this CM feature. https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#mandatory-features
