### ISSUE TITLE
ClientPIN tests issue on PinPolicy check

### ISSUE THREAD

**Issue by carov0610** [fido-alliance/conformance-test-tools-resources#686]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [X] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [X] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
FIDO Conformance Tools v1.7.2 || CTAP2.1

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [X] Windows 10 20H2
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
In test P-1 of Authr-ClientPin1-PinPolicy.js, a PIN is randomly generated but without regard to UTF-8 encryption.
It leads to card returns an error CTAP2_ERR_PIN_POLICY_VIOLATION to command setPin and test is fail as expected status is CTAP1_ERR_SUCCESS

**Comment by nuno0529** [comment]
add the same issue ref. https://github.com/fido-alliance/conformance-test-tools-resources/issues/607
