### ISSUE TITLE
Incorrect attestationTypes entry in "Virtual RSA PKCS 1.5 SHA256 FIDO2 Conformance Testing CTAP2 Authenticator with SafetyNet attestation.json"

### ISSUE THREAD

**Issue by sbweeden** [fido-alliance/conformance-test-tools-resources#687]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ X] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.7.3

## What is the OS and the version are you running?

For desktop tools
- [ X] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

Currently, if a FIDO2 Server decides to check that the attestation it receives contains an attestation type "permitted" in the `attestationTypes` list of the associated metadata file, then the following test case fails:
```
Server-ServerAuthenticatorAttestationResponse-Resp-B Test server processing "android-safetynet" attestation
P-1 Send a valid ServerAuthenticatorAttestationResponse with "android-safetynet" attestation, and check that server succeeds
```

The metadata file "Virtual RSA PKCS 1.5 SHA256 FIDO2 Conformance Testing CTAP2 Authenticator with SafetyNet attestation.json" contains:
```
    "attestationTypes": [
        "anonca"
    ],
```
when it should most likely contain:
```
    "attestationTypes": [
        "basic_full"
    ],
```

**Comment by Kieun** [comment]
This is more like the spec issue rather than the bug.
Related to this issue: https://github.com/w3c/webauthn/issues/1819
