### ISSUE TITLE
V1.7.2 CTAP2.1 CredProtect Tests Deviate From Standard for AlwaysUv Authenticator

### ISSUE THREAD

**Issue by BryanJacobs** [fido-alliance/conformance-test-tools-resources#688]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [X] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [X] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

V1.7.2

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [X] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

The CredProtect tests, before each test, attempt to disable the `alwaysUv` feature using the `AuthenticatorConfig` commands. They do this even if the authenticator does not *support* `AuthenticatorConfig` (no advertisement in the GetInfo response). They also don't respond positively to the explicitly-standard-blessed behavior of rejecting an attempt to disable `alwaysUv` with `CTAP2_OPERATION_DENIED`.

This deviates from the spec for several reasons:

1. CTAP2.1 authenticators don't need to support AuthenticatorConfig (it is entirely optional)
2. Authenticators shouldn't need to, per the CTAP2.1, support disabling `alwaysUv` (this is a SHOULD in the standard, not a MUST)
3. `credProtect` test should test that the authenticator behaves appropriately *with* `alwaysUv` enabled, verifying that a `credProtect` level of 3 (UV required before use) is returned in that situation

The `alwaysUv`-disabled tests should check if AuthenticatorConfig is supported, and if it is not, skip. If it is, attempt to disable `alwaysUv`, and if that returns `CTAP2_OPERATION_DENIED`, skip. If it succeeds, run the test.

There should also be `alwaysUv`-enabled `credProtect` tests which verify correct behavior after enabling `alwaysUv`.

**Comment by herrjemand** [comment]
Addressed in v1.7.10

**Comment by herrjemand** [comment]
https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.7.11/

**Comment by BryanJacobs** [comment]
The credProtect tests now toggle alwaysUv at the start of the run for authenticators that are off. This makes them fail on authenticators that support alwaysUv, allow toggling it, and default it to off @herrjemand .

The tests always expect an assertion without a PIN provided to succeed for credProtect levels 1 and 2, but that's not a correct assumption if alwaysUv is enabled. And the test setup can end up *enabling* alwaysUv now.
