### ISSUE TITLE
fido2-interop-webapp always requires a makeCredReq.excludeCredentials iterable

### ISSUE THREAD

**Issue by pmlopes** [fido-alliance/conformance-test-tools-resources#689]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [x] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

https://github.com/fido-alliance/fido2-interop-webapp/tags master

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [ ] Windows
- [x] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

The new conformance tools also mention a required interop app. While trying to run the test I observe that the tests are probably too strict:

https://github.com/fido-alliance/fido2-interop-webapp/blob/master/index.html#L429

When asking for a make credentials options, if on my server there is no knowledge on a given user handle yet, why should the interop expect that the property is present and iterable. In my case it is `undefined` as it was never provided by the server so I get:

```
TypeError: makeCredReq.excludeCredentials is not iterable
```

According to the spec: https://www.w3.org/TR/webauthn-2/#dictionary-makecredentialoptions

This field should default to empty array, even https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/create states it is an optional field.

So I'm not sure this is correct to expect that interop implementations always provide it.

**Comment by herrjemand** [comment]
For conformance testing API we require server to always return array of credentials
