### ISSUE TITLE
V1.7.6 CTAP2.0 || ClientPin protocol 1 || (F-2)  newpin length error

### ISSUE THREAD

**Issue by choojun13** [fido-alliance/conformance-test-tools-resources#691]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [x] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
V1.7.6
## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [x] Android

## Issue description

Ctap2.0 ClientPin protocol 1
In case test F-2 , the wrong newpin value (over 63 length) should come, but sometimes the correct value(4 ~ 63) is passed and the test fails.

**Comment by jmichelp** [comment]
I have the same issue here and my take on this issue is that the new PIN is assigned with random values, including `0x00` bytes.
For CTAP2.0, any `0x00` byte encountered from the beginning of the buffer will determine the PIN length while CTAP2.1 asks to discard trailing `0x00` bytes.
The tool should ensure that `generateRandomBuffer()` function fills the buffer with non-null bytes only when used for testing PIN lengths

**Comment by herrjemand** [comment]
I can not reproduce it since we do not generate pin arrays that start with 0x00. Additionally FIDO uses deterministic CBOR so authr should be able to check output length matches.

**Comment by jmichelp** [comment]
Maybe my comment was not precise enough: the buffer doesn't need to start with a `0x00` byte. It only needs to contain one, which is totally possible as the tool is using a regular RNG for that.
CTAP2.0 specification asks to iterate for the buffer from left to right and stop at the first `0x00` byte to determine the PIN length. So a buffer such as `42 42 42 00 42 42 42 ... 42` (64 bytes total) would make a PIN length of 3 against CTAP2.0 spec.
CTAP2.1 fixes that by asking to strip trailing `0x00` bytes instead, which means the implementation is expected to go from right to left and stop at the first non-null byte.

**Comment by herrjemand** [comment]
Ok, this is now addressed

**Comment by herrjemand** [comment]
Latest build https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.7.11/
