### ISSUE TITLE
AuthenticBioEnrollment: Power Off/ Power On on each command enrollCaptureNextSample in Conformance test tool

### ISSUE THREAD

**Issue by carov0610** [fido-alliance/conformance-test-tools-resources#693]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

FIDO Conformance Tools v1.7.6 

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
In test P-2 (Keep sending enrollCaptureNextSample(0x02) for the specified templateId) commands sendValidCTAP_CBOR (,) in captureNext function are sent without parameter {'dontResetCard': true}. It results that power is cut between two commands that prevents biosensor to progress the enrollment process.

Note: is the command refreshPUATWithPermissionBE necessary in this case?
This does not match process description in the specification (Platform sends authenticatorBioEnrollment command with following parameters to continue enrollment in a loop till remainingSamples is zero or authenticator errors out with unrecoverable error or platform wants to cancel current enrollment:)

**Comment by herrjemand** [comment]
this is now resolved in 1.7.11. Build should be today/tomorrow

**Comment by herrjemand** [comment]
Latest build https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.7.11/
