### ISSUE TITLE
https://mds3.certinfra.fidoalliance.org is offline

### ISSUE THREAD

**Issue by iamcarbon** [fido-alliance/conformance-test-tools-resources#696]
Do we have any guidance or updates on when https://mds3.certinfra.fidoalliance.org will be back online?

**Comment by pheimfido** [comment]
Dear Jason, 

 

I’ll provide a status update on this shortly. 

 

Thank you, 

Paul

 

Paul Heim | Certification Director | FIDO Alliance

T: +1 623-200-3994

 ***@***.***> ***@***.*** |  <http://www.fidoalliance.org/> www.fidoalliance.org

 

From: Jason Nelson ***@***.***> 
Sent: Monday, January 16, 2023 3:38 PM
To: fido-alliance/conformance-test-tools-resources ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fido-alliance/conformance-test-tools-resources] https://mds3.certinfra.fidoalliance.org is offline (Issue #696)

 

Do we have any guidance or updates on when https://mds3.certinfra.fidoalliance.org will be back online?

**Comment by herrjemand** [comment]
@iamcarbon will be up today

**Comment by PaulVanStaden** [comment]
Looks like this issue can be resolved.
