### ISSUE TITLE
App crashes on MacOS

### ISSUE THREAD

**Issue by AraHovakimyan** [fido-alliance/conformance-test-tools-resources#697]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ +] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] CTAP2.0

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
- FIDO Alliance - Certification Conformance Testing Tools-1.7.9

## What is the OS and the version are you running?
- macOS Ventura(13.1)

For desktop tools
- [ ] OSX

## Issue description

After opening the application on MacOS, after about 20-30 seconds the application crashes. This happens no matter if a process is running or not. Just opening and leaving the app open causes a crash, too. There was a similar issue reported, but the crash log didn't give sufficient information. We tried running it using Terminal, and I think the Terminal log might be more informative and it's attached hereby.
We suspect that the issue might be related to having the tool running in the same network on multiple devices.

[log.txt](https://github.com/fido-alliance/conformance-test-tools-resources/files/10577098/log.txt)

**Comment by herrjemand** [comment]
@AraHovakimyan do you still have this issue? I can not reproduce it.

I have M1 MacPro 13.0.1

**Comment by herrjemand** [comment]
@AraHovakimyan ...we do not check if there multiple FIDO tools on the network? And tools only expose some local HTTP interface... were you able to check that tools are crashing explicitly when two instances are running on the same network?

**Comment by herrjemand** [comment]
Seems like the issue you are having is to do with BLE stack. I will take a look

**Comment by herrjemand** [comment]
@AraHovakimyan I tested on M2 Macbook Air Ventura 13.4 and it runs without any issues.
