### ISSUE TITLE
Authr-CredentialManagement-EnumerateRPs Test authenticatorCredentialManagement(0x0A) command support for discoverable credential metadata and enumeration functionality for RPs doesn't respect chapter 6 in CTAP2.1

### ISSUE THREAD

**Issue by Molyna** [fido-alliance/conformance-test-tools-resources#701]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [X] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [X] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.7.9

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [X] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

The tests in `Authr-CredentialManagement-EnumerateRPs Test authenticatorCredentialManagement(0x0A) command support for discoverable credential metadata and enumeration functionality for RPs` doesn't seem to respect stateful commands. The tests seems to run so P-2 generates a call to Credential Management subcommand 2 (`enumerateRPsBegin`). After that succeeds P-3 start, by generating a new `pinUVAuthToken` through a `ClientPin` request. But if we look at [Chapter 6](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#authenticator-api), which covers stateful commands, we get 

> The authenticator MAY maintain state based on the assumption that each [stateful command](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#stateful-commands) is exclusively preceded by either another instance of the same command, or by the corresponding [state initializing command](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#state-initializing-command), and no more than 30 seconds will elapse between such commands. If this pattern is violated then the authenticator MAY fail any [stateful command](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#stateful-commands) with the error CTAP2_ERR_NOT_ALLOWED. Here, “exclusively preceded” means that no other [authenticator operation](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#authenticator-operation) occurs in between. An authenticator MAY assume this globally, even when the transport-specific binding provides for independent streams of platform commands (e.g. [§ 11.2.3 Concurrency and channels](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#usb-channels)).

As the test triggers a clientPin call prior to the `enumerateRPsGetNextRP` an authenticator may return a 0x30 instead of the expected 0x00 return value.

The same situation seems to apply to `Authr-CredentialManagement-EnumerateCredentials Test authenticatorCredentialManagement(0x0A) command support for discoverable credential enumeration` and test P-2

**Comment by herrjemand** [comment]
@Molyna Thanks for reporting. New build in few hours

**Comment by herrjemand** [comment]
Latest build https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.7.11/
