### ISSUE TITLE
CTAP2_ERR_PUAT_REQUIRED at HMAC test

### ISSUE THREAD

**Issue by jay4111335** [fido-alliance/conformance-test-tools-resources#702]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

FIDO Conformance Tools v1.7.9

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

I am using Yubikey Bio to run conformance test, P-2 failed

P-2 Send a valid CTAP2 authenticatorMakeCredential(0x01) message, "extensions" containg a valid "hmac-secret" set to true, wait for the response, and check that Authenticator returns CTAP1_ERR_SUCCESS(0x00) error code, with extensions payload containing 'hmac-secret' field set to true

Error: Expected authenticator to succeed with CTAP1_ERR_SUCCESS(0). Got CTAP2_ERR_PUAT_REQUIRED(54)
    at eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:3364:19)

[https://ibb.co/V9WQ9Gv](url)

The error CTAP2_ERR_PUAT_REQUIRED occurs and it seems to be alwaysUv should be turned off but it's not. 

Can refer to this discussion here[https://groups.google.com/a/fidoalliance.org/g/fido-dev/c/3WoT39Jm5pc](url)

**Comment by herrjemand** [comment]
@jay4111335 is this still issues in v1.7.11 for you?

**Comment by herrjemand** [comment]
This should now be addressed @jay4111335 https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.7.14/
