### ISSUE TITLE
v1.7.10 || FIDO2 Server MDS tests issue - https://mds3.fido.tools/getTestMetadata returns 404 

### ISSUE THREAD

**Issue by ChuangRicky** [fido-alliance/conformance-test-tools-resources#703]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X]  I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [X] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [X] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.6.42, 1.7.10

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [X] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
FIDO Conformance Tools v1.7.10 || FIDO2 Server - MDS3
Metadata Service Tests are failing. The conformance tool tries to access the URL https://mds3.fido.tools/getTestMetadata, but it returns HTTP status code 404.

![mds3_fake_data_test](https://user-images.githubusercontent.com/128689698/227169242-70d8fb11-9fc8-4cea-bb22-4a976b12ed49.jpg)

![console_error_F1](https://user-images.githubusercontent.com/128689698/227169234-1da97de2-8895-478e-964b-bf27f9c333a1.jpg)

![getTestMetadata_404](https://user-images.githubusercontent.com/128689698/227169240-63bf3004-11d8-40b5-9a04-7efb27d5382a.jpg)

The original test version was 1.6.42
Refer to issue [#698](https://github.com/fido-alliance/conformance-test-tools-resources/issues/698)  to upgrade the version to 1.7.10
the same problem still exists

**Comment by herrjemand** [comment]
Ok, yes. This is Windows build issue. This is now resolved

**Comment by herrjemand** [comment]
Latest build https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.7.11/
