### ISSUE TITLE
Tool keeps sending keep-alive messages after a test has timed out waiting for user interaction

### ISSUE THREAD

**Issue by Molyna** [fido-alliance/conformance-test-tools-resources#704]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [x] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.7.10

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
During BLE testing we are seeing some weird behavior regarding keep-alive messages that keep getting sent even if the tool has moved onto a new tests, meaning we have multiple keep-alive messages been run at the same time. 

For the reproducing, we have a BLE based device with built-in UV. So given for example the following generated FIDO request

```a501582041754262dfdaa4c6585e254d4c90750aa9fe2cb964cae327b4fc7f91e5c7026d02a262696477706173736f6e66727569746e6563746172696e652e6e69646e616d657829546865204578616d706c6520436f72706f726174696f6e20776974682066616b6520646f6d61696e2103a362696458202bd53f04dd35beb566ff2ddca9e012bdabd34a308367f288a2a8ece74d80457c646e616d65781d73686172796c73656775696e4073707572696f75737368696e792e62746b646973706c61794e616d656d53686172796c2053656775696e0481a263616c672664747970656a7075626c69632d6b657907a1627576f5```

the device should end up doing a user verification. During this there is a number of keep alive messages happening, in our case about 40 or 8 seconds worth. After this the test times out. Here the tool then triggers a turn off for notifications on the controlPoint. Less than a second after this the tool then turns on notifications on the controlPoint again and we get a new flow of keep alive messages. 

At this point the tool starts a new tests and sends us a new request

```a501582099d5bb00deb85131153a8f9ded14ef968ae081fcf65ca969c531e68003fd679202a26269646d746f6d61746f776169742e6c69646e616d657829546865204578616d706c6520436f72706f726174696f6e20776974682066616b6520646f6d61696e2103a36269645820529920b5bf580e74a7160a7e94fb74999cd25e2e16249b5d9ab4cfbb6a94a9b7646e616d65781c6e616e6e69652e66656e6e65724073617473756d617761726d2e696d6b646973706c61794e616d656d4e616e6e69652046656e6e65720481a263616c672664747970656a7075626c69632d6b657907a1627576f5```

However the device is still awaiting user verification from the previous request and we can see that the rate of keep-alive has now doubled so it looks like the test tool is now running both tests over BLE simultaneously. This leads to the tool no longer being able to keep track of the requests it is sending and will fail every test afterwards. This seems to happen as the tool is now mixing keep-alive messages into requests or not expecting a keep-alive message  being returned at a certain point.

Things behave correctly if the user verification is completed within 8 seconds.

**Comment by herrjemand** [comment]
This one in works, and will be resolved by the end of the week
