### ISSUE TITLE
AuthenticBioEnrollment: remaining Power Off/ Power On on each command enrollCaptureNextSample in Conformance test tool

### ISSUE THREAD

**Issue by carov0610** [fido-alliance/conformance-test-tools-resources#705]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [X] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [X] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
FIDO Conformance Tools v1.7.11

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [X] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
In test P-2 If authenticator supports BioEnrollment API: Send authenticatorBioEnrollment(0x09) with enrollBegin(0x01) with supported modality. Check that command succeeds. Keep sending enrollCaptureNextSample(0x02) for the specified templateId, and check that: (b) remainingSamples(0x06) - number, and is the same or less than previous request (c) lastEnrollSampleStatus(0x05) - number, a valid BE status code When remainingSamples is 0, and lastEnrollSampleStatus is CTAP2_ENROLL_FEEDBACK_FP_GOOD(0x00)
power off / power on occurs between each command enrollCaptureNextSample. It prevents the enrollment to progress (linked to issue #693 closed)

**Comment by carov0610** [comment]
It seems the problem leads in 
    it(`P-2

        If authenticator supports BioEnrollment API: Send authenticatorBioEnrollment(0x09) with enrollBegin(0x01) with supported modality. Check that command succeeds.

        Keep sending enrollCaptureNextSample(0x02) for the specified templateId, and check that:
            (b) remainingSamples(0x06) - number, and is the same or less than previous request
            (c) lastEnrollSampleStatus(0x05) - number, a valid BE status code

        When remainingSamples is 0, and lastEnrollSampleStatus is CTAP2_ENROLL_FEEDBACK_FP_GOOD(0x00), stop

    `, function() {
        if(!bioEnrollSupported) {
            this.skip();
        }

        const subCommandParams = {
            0x03: 10000 // TODO investigate
        }

        const subCommandParams_bytes = navigator.fido.fido2.cbor.JSONToCBORArrayBuffer(subCommandParams);

        let templateId = undefined
        return sendValidCTAP_CBOR(BioEnrollment21_GenerateCMD({
            'modality'          : BioEnrollment21_Modalities.fingerprint,
            'subCommand'        : BioEnrollment21_ReqSubCommand.enrollBegin,
            'subCommandParams'  : subCommandParams,
            'pinUvAuthProtocol' : pinUvAuthProtocol,
            'pinUvAuthParam'    : ClientPinLatest_core_authenticate_raw(pinUvAuthToken, pinUvAuthProtocol, mergeArrayBuffers(
                new Uint8Array([BioEnrollment21_Modalities.fingerprint, BioEnrollment21_ReqSubCommand.enrollBegin]),
                subCommandParams_bytes
            ))

        }))
        .then((response) => {
            templateId = response.cborResponseStruct[BioEnrollment21_RespParams.templateId];
            return captureNext(templateId)
        })
    })


, {'dontResetCard': true}) is missing

**Comment by herrjemand** [comment]
@carov0610, yes you correct. New build out Wednesday

**Comment by herrjemand** [comment]
https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.7.12/
