### ISSUE TITLE
PIN verification/management logic

### ISSUE THREAD

**Issue by pheimfido** [fido-alliance/conformance-test-tools-resources#707]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [X] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

The latest version (1.7.11) generates an error during our testing due to a change in the PIN management/logic during the script's execution.
 
The older version of test tool performs user PIN verification before running the following commands, whereas the newer version does not perform this verification step.
 
The test cases for P-3 and P-2 failed because the command authenticatorCredentialManagement(0x0D) with enumerateRPsGetNextRP(0x03) and authenticatorCredentialManagement(0x0D) with enumerateCredentialsGetNextCredential(0x05) did not perform user PIN verification, resulting in the failure of the tests.
 
================
P-3 If authenticator supports Credential Management API: Send authenticatorCredentialManagement(0x0D) with enumerateRPsGetNextRP(0x03), and check that result: (a) Result.rp is present and of type MAP (b) [Result.rp.id](https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fResult.rp.id&c=E,1,VZv0wReAUkgDY0UKC_hkuNP3Q7JqTejhvji3bYEYO_1zIdjUEKrKD4S0_eifzwEkjGtYxytEGBNFltLCE18u-T4NMdWtirP5HnWN2Ea7c7qpIf-vzoFKq4IlCXY,&typo=1&ancr_add=1) is present and is of type String. (c) [Result.rp.id](https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fResult.rp.id&c=E,1,gvVrgWx1Zn3IPtNJUum9lCV_VYn9lGNFlLkRHrjn4_MMSo737YHsq3tSuzbeS3V6nDe86HPp9ZX3t3MJ9QCZJu59ORb8hKxl8h29gFUM4zykKFeR_QvkiWzRxA,,&typo=1&ancr_add=1) is in a list of known rpIDs. (d) Result.rpIDHash is a valid SHA-256 hash of [Result.rp.id](https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fResult.rp.id&c=E,1,Ebbrd8_S8_jIWVIKh1jHAMsKvfoCVGrrWrGVDYtw9uBkBYad3iTVKIjCtnFdSBO376cAgOWfNX0vPDIp6TEJwq48YyGbKEVYtbDJ0rbVUmhjJzCCzw,,&typo=1&ancr_add=1), and is of type BYTESTRING.‣ 
Error: Expected authenticator to succeed with CTAP1_ERR_SUCCESS(0). Got CTAP2_ERR_MISSING_PARAMETER(20)
    at eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:3364:19)
 
P-2 If authenticator supports Credential Management API: Create two new discoverable credentials. Send authenticatorCredentialManagement(0x0D) with enumerateCredentialsGetNextCredential(0x05), and make sure that: (a) Response.credentialID is of type PublicKeyCredentialDescriptor, and matching previously recorded credentialID (b) Response.user is of type PublicKeyCredentialUserEntity, and at least contains id, that matches previously recorded (c) Response.publicKey is a COSE_Key and matches previously recorded (d) Response.totalCredentials is undefined‣
Error: Expected authenticator to succeed with CTAP1_ERR_SUCCESS(0). Got CTAP2_ERR_MISSING_PARAMETER(20)
    at eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:3364:19)
================

**Comment by herrjemand** [comment]
@pheimfido yes, this is expected behaviour. enumerateCredentialsGetNextCredential and enumerateRPsGetNextRP are session bound commands that rely on previously authenticated initiator.

**Comment by herrjemand** [comment]
>
