### ISSUE TITLE
Missing pinUvAuthToken fetch in Authr-CredentialManagement-EnumerateRPs Test P-2

### ISSUE THREAD

**Issue by nagreme** [fido-alliance/conformance-test-tools-resources#714]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

v1.7.11

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows 11
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

Authr-CredentialManagement-EnumerateRPs Test P-2 was passing on 1.7.10 but is now failing on 1.7.11 (same authenticator implementation) with pin auth invalid error (CTAP2_ERR_PIN_AUTH_INVALID).

Cause seems to be that the test in the 1.7.11 version of the tool doesn't re-fetch the pinUvAuthToken (`Generating test PUAT...`, i.e. getKeyAgreement + getPinToken) before sending the request unlike other tests in the same category.

v1.7.10

![image](https://github.com/fido-alliance/conformance-test-tools-resources/assets/25629116/0c259c64-3bdd-4923-bd76-4a3b96a6402e)

v1.7.11

![image](https://github.com/fido-alliance/conformance-test-tools-resources/assets/25629116/ed21b90d-97d7-40d1-8178-c4d0662ec004)

If we can just add that back in the test it would resolve this. 

Otherwise if this removal was intentional can you provide an explanation/reason?

**Comment by herrjemand** [comment]
@nagreme is that for NFC?

**Comment by nagreme** [comment]
I have the same error on both:
- Identiv uTrust 4701 F 
- HID Omnikey 5022 CL

**Comment by herrjemand** [comment]
Ok, confirmed and resolved.!

**Comment by nagreme** [comment]
Awesome thank you! 🙂

**Comment by herrjemand** [comment]
latest build: https://builds.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.7.14/
