### ISSUE TITLE
Incorrect description on FIDO2 Server test case 

### ISSUE THREAD

**Issue by sbweeden** [fido-alliance/conformance-test-tools-resources#715]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [X ] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [ X] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.7.12

## What is the OS and the version are you running?
MacOS

For desktop tools
- [X ] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
It's very obviously a cut/paste error here: 
https://github.com/fido-alliance/fido2-server-conformance-module/blob/main/tests/Server/MakeCredential/Server-ServerAuthenticatorAttestationResponse-Resp-7.js#L34

That test description says:
`Send a valid ServerAuthenticatorAttestationResponse with SELF(SURROGATE) "packed" attestation, and check that server succeeds`
however the test is for a "none" attestation.

**Comment by herrjemand** [comment]
Resolved
