### ISSUE TITLE
Invalid metadata file for Android Keystore Server test

### ISSUE THREAD

**Issue by sbweeden** [fido-alliance/conformance-test-tools-resources#716]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [X] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [X] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.7.12

## What is the OS and the version are you running?
MacOS

For desktop tools
- [X] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
For test:
Server-ServerAuthenticatorAttestationResponse-Resp-A Test server processing "android-key" 
    P-1 Send a valid ServerAuthenticatorAttestationResponse with "android-key" attestation, and check that server succeeds

Code here: https://github.com/fido-alliance/fido2-server-conformance-module/blob/main/tests/Server/MakeCredential/Server-ServerAuthenticatorAttestationResponse-Resp-A.js#L27

You can see this uses a metadata file with AAGUID: 550e4b54-aa47-409f-9a95-1ab76c130131

Which corresponds to metadata file: https://github.com/fido-alliance/fido2-server-conformance-module/blob/main/metadata/CTAP2Secp256r1AndroidAttestation.metadata3.json#L23

Notice that the `attestationTypes` element contains *only* `anonca`. It should be `basic_full` since Android Keystore attestations are a type of Basic attestation (see https://w3c.github.io/webauthn/#sctn-android-key-attestation)

**Comment by iirachek** [comment]
Resolved
