### ISSUE TITLE
Adopt residentKey param deprecating requireResidentKey

### ISSUE THREAD

**Issue by mkkhedawat** [fido-alliance/conformance-test-tools-resources#717]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

The old issue is outdated and closed - https://github.com/fido-alliance/conformance-test-tools-resources/issues/676

## What protocol are you implementing?

- [x] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [x] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.7.14

## What is the OS and the version are you running?

For desktop tools
- [x] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

Test which checks for requireResidentKey fails  - 
```
AssertionError: Response.authenticatorSelection MUST be set to the requested authenticatorSelection! Expected "{"residentKey":"preferred","userVerification":"preferred"}" to equal "{"requireResidentKey":false,"userVerification":"preferred"}": expected { Object (residentKey, userVerification) } to deeply equal { Object (requireResidentKey, userVerification) }
    at n.eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:4529:16)
```

Now that requireResidentKey is deprecated in favour of discoverable credentials, Can we please update the test ?

[PS - This tool is fantastic and act as primary layer of testing for me]

**Comment by pheimfido** [comment]
Updated assignees: removed Yuriy Ackermann, assigned @iirachek
