### ISSUE TITLE
Creation of key with ES512 algorithm expects 64 bytes for public key x and y component length instead of 66 bytes based on P-521 curve

### ISSUE THREAD

**Issue by ryarana** [fido-alliance/conformance-test-tools-resources#723]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.7.14

## What is the OS and the version are you running?
Windows 10
For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
Based on WebAuth, https://www.w3.org/TR/webauthn-2/#sctn-alg-identifier
_Keys with algorithm ES512 (-36) MUST specify P-521 (3) as the [crv](https://tools.ietf.org/html/rfc8152#section-13.1.1) parameter and MUST NOT use the compressed point form._

While testing using the self-conformance tool v1.7.14 for CTAP 2.1, I encountered the following error:
_Authr-MakeCred-Resp-1 Test registration response, and “packed” attestation:
P-02   AssertionError: For ES512 x coefficient MUST be exactly 64 bytes long!: expected 66 to equal 64 at n.eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:6482:28)_

The authenticator under test returned 66 bytes for the x and y component for ES512 (which is correct for P-521 curve) but the tool expects 64 bytes. In addition, the self-conformance tool code snippet below expects P-521/secp521r1 but its expected length is wrong.
_…
} else if(COSE_ALG_TO_FIDO_ALG_SHORT[keyStruct[COSE_KEYS.alg]] === ‘secp521r1_ecdsa_sha512_raw’ {
   assert.strictEqual(keyCBORStruct[COSE_KEYS.x].byteLength, 64, ‘For ES512 x coefficient MUST be exactly 64 bytes long!’);
   assert.strictEqual(keyCBORStruct[COSE_KEYS.y].byteLength, 64, ‘For ES512 y coefficient MUST be exactly 64 bytes long!’);
}
…_

**Comment by iirachek** [comment]
Sorry for the wait. This issue has been addressed and a fix will be available in the upcoming build. 
I'll notify you, when the build is published.
