### ISSUE TITLE
UVM test fails with metadata mentioning multiple matcher protection

### ISSUE THREAD

**Issue by serianox** [fido-alliance/conformance-test-tools-resources#730]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

When testing an authenticator with the following UVM
```bash
82            # array(2)
   83         # array(3)
      01      # unsigned(1) presence_internal
      0A      # unsigned(10) key_protextion_hardware | key_protection_secure_element
      04      # unsigned(4) matcher_protection_on_chip
   83         # array(3)
      19 0800 # unsigned(2048) passcode_external
      0A      # unsigned(10) key_protextion_hardware | key_protection_secure_element
      01      # unsigned(1) matcher_protection_software
```

The metadata is set accordingly to the following
```json
   "matcherProtection": [
      "software",
      "on_chip"
   ],
```

The test _Metadata-Stmt-1_ _P-16_ fails at _ctap2.1-conformance-module/tests/CTAP2/Metadata/Metadata-Stmt-1.js_:492 with the following error
> AssertionError: "on_chip" flag can not be combined with "software" flag!: expected [ 'software', 'on_chip' ] to not include 'on_chip'
>    at n.eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:2027:20)

The [specification](https://fidoalliance.org/specs/mds/fido-metadata-statement-v3.0-ps-20210518.html) mentions
> matcherProtection, of type DOMString[]
> The list of matcher protections supported by the authenticator. Must be set to the complete list of the supported MATCHER_PROTECTION constant case-sensitive string names defined in the FIDO Registry of Predefined Values [[FIDORegistry]](https://fidoalliance.org/specs/mds/fido-metadata-statement-v3.0-ps-20210518.html#biblio-fidoregistry). See section "Matcher Protection Types", e.g. "on_chip". This value MUST NOT be empty.

The test expect the list to contain only one element. This is probably a leftover of the MDS2 tests where the values were mutually exclusive.

**Comment by iirachek** [comment]
@serianox  I believe the tests are correct to be expecting only one element, since the values are still indirectly mentioned as being mutually exclusive.

The [specification](https://fidoalliance.org/specs/mds/fido-metadata-statement-v3.0-ps-20210518.html#dom-metadatastatement-matcherprotection) contains the following note below the definition of `matcherProtection` member of metadata:
>If multiple user verification methods ("matchers") are implemented, then this value must reflect the weakest implementation of all user verification methods.

Which means that between "software" and "on_chip" only one should be listed, with "software" being the weakest among them.

Additionally (though not as relevant), in the [registry of predefined values](https://fidoalliance.org/specs/common-specs/fido-registry-v2.1-ps-20191217.html#matcher-protection-types) the "on_chip" type is noted as:
> Mutually exclusive in authenticator metadata with MATCHER_PROTECTION_TEE, MATCHER_PROTECTION_SOFTWARE

**Comment by serianox** [comment]
@iirachek 

I'm not sure what the author wanted. This field is a list, so multiple values are expected (emphasis is from the original text)
> Must be set to the _complete list_ of the supported MATCHER_PROTECTION constant

And then right below in a note
> If multiple user verification methods ("matchers") are implemented, then this value must reflect the weakest implementation of all user verification methods.

I would assume that ["on_chip", "software"] is perfectly fine and also reflects the weakest implementation because "software" is listed.

But then as you mentioned, the registry states that some values for MATCHER_PROTECTION are mutually exclusive. However, I do think that the value being exclusive is only valid for the bitfields in UAF, not the textual representation of MDS3.

---

Now, _assuming that the values are indeed exclusive_, I change my metadata statement to the following since I support passcode_external and presence_internal, 
```json
   "matcherProtection": [
      "software"
   ],
```

The test fails differently: when verifying the UVM value for 
```
   83         # array(3)
      01      # unsigned(1) presence_internal
      0A      # unsigned(10) key_protextion_hardware | key_protection_secure_element
      04      # unsigned(4) matcher_protection_on_chip
```
it expects to find "on_chip" in the list matcherProtection. But since the list contains only one element, the weakest, it can't because only "software" is listed.

Here, I think the test should:
- accept the values "software", "tee", "on_chip" when the uvm is MATCHER_PROTECTION_ON_CHIP
- accept the values "software", "tee" when the uvm is MATCHER_PROTECTION_TEE
- accept the value "software" when the uvm is MATCHER_PROTECTION_SOFTWARE

**Comment by iirachek** [comment]
I've asked internally for additional clarifications regarding this part of the specification. Until then, this issue is on hold.

**Comment by serianox** [comment]
Thanks. In the meantime I'll dig a bit more and try alternative scenarios.

**Comment by pheimfido** [comment]
Yes, as mentioned by Illia, this issue has been raised to the FIDO MDS TWG Leadership for feedback and guidance to be provided. We'll update this issue as soon as a resolution is reached.  - Paul Heim, Certification Director, FIDO Alliance

**Comment by iirachek** [comment]
@serianox 

In short, your original implementation is correct. The normative clauses and the data type of `matcherProtection` support multiple entries. Thus for the UVM provided in your question, the correct metadata statement will contain both "on_chip" and "software".

The related tests were updated in the new build (1.7.17) to account for that.

**Comment by serianox** [comment]
@iirachek Thanks! I've read the PR and it looks good to me. I'll test it tomorrow as soon as possible to give feedbacks.

**Comment by serianox** [comment]
I apologize for the delay, I had a little setback.

I did test fully and now the test is passing as expected. 👍
