### ISSUE TITLE
"fido-conformance-tools-ionic-v1.6.2.ipa" Installation Issue.

### ISSUE THREAD

**Issue by sunpie7** [fido-alliance/conformance-test-tools-resources#731]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [✔️] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [✔️] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.6.2

## What is the OS and the version are you running?
OS 16.6

For desktop tools
- [ ] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [✔️] iOS
- [ ] Android

## Issue description

After installing the file with App Configurator and attempting to run the app, I got the following error:
"This app cannot be installed because its integrity could not be verified."

Can you explain how to install it?

**Comment by litaoyu** [comment]
I had the same problem
Is there a solution

**Comment by herrjemand** [comment]
Please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org) your UDID and we will add them to the latest build

**Comment by litaoyu** [comment]
> Please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org) your UDID and we will add them to the latest build

Already sent. Thank you.

**Comment by iirachek** [comment]
@sunpie7 @litaoyu 

The UDIDs were registered in the system. Now you will be able to launch mobile conformance tools on these devices.
Please, redownload the file for iOS to ensure that the issue is resolved.
