### ISSUE TITLE
Supporting Reset on NFC and BLE is optional

### ISSUE THREAD

**Issue by jovasco** [fido-alliance/conformance-test-tools-resources#737]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [X] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [X] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

All versions are affected.

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [X] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

Supporting the Reset command is optional on NFC and BLE [See spec](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#authenticatorReset).
However, if you do not support the reset command on those transports, you cannot get past the tests.

**Comment by herrjemand** [comment]
Just clarify: It is optional if you support any other transport that
supports reset:

However this command MUST be supported on at least one transport. If the
USB HID transport is supported then this command MUST be supported on that
transport.

So if your device does support ONLY NFC or ONLY BLE then reset must be
supported.

In other cases it can be supported by only one transport.

Yuriy Ackermann
FIDO, Identity, Standards
skype: ackermann.yuriy
github: @herrjemand <https://github.com/herrjemand>
twitter: @herrjemand <https://twitter.com/herrjemand>
medium: @herrjemand ***@***.***>

**Comment by jovasco** [comment]
That is correct, Yuriy, but the tests currently assume that if you want to test NFC/BLE, reset over NFC/BLE works too.
I am aware this isn't an easy thing to solve...
