### ISSUE TITLE
Tool version 1.7.18: Error when starting to run the tests

### ISSUE THREAD

**Issue by carov0610** [fido-alliance/conformance-test-tools-resources#747]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [X] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [X] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.7.18

## What is the OS and the version are you running?
Windows 10 Enterprise / 10.0.19044 Build 19044

For desktop tools
- [ ] OSX
- [X] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
When starting to run tests on an authenticator, tool fails with error 
"Error while executing tests. Error message: SyntaxError: Identifier 'PinUvAuthProtocol1' has already been declared"
execution stops

**Comment by iirachek** [comment]
Uploaded a new build (v1.17.18-1) with a hotfix for this issue.

**Comment by jovasco** [comment]
> Uploaded a new build (v1.17.18-1) with a hotfix for this issue.

That should probably be v1.7.18-1 ?

**Comment by iirachek** [comment]
> That should probably be v1.7.18-1 ?

Oops, mistyped the number. :sweat_smile:
It is v1.7.18-1 indeed.
