### ISSUE TITLE
Submit Result results in 500 error from server

### ISSUE THREAD

**Issue by Molyna** [fido-alliance/conformance-test-tools-resources#751]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [X] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [X] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.7.19

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [X] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

Hitting submit results with a metadata that has the same AAGUID as a previously verified authenticator results in a 500 error response with a body stating that the AAGUID already exists. 

Given WebAuthn states that " The AAGUID MUST be chosen by the manufacturer to be identical across all substantially identical authenticators made by that manufacturer" the expectation would be that the submit would work on the same AAGUID given that `firmwareVersion` and `authenticatorVersion` have been incremented from the currently stored version.

**Comment by iirachek** [comment]
Perhaps this would make sense for metadata that is not yet publicly available to account for potential changes during development, before certification is issued.

Since this is more of an MDS3 domain than conformance tools, I'll ask if this is something they are interested in implementing.

**Comment by iirachek** [comment]
> There is also consideration if the tool should display the message body of the response as well

This will be addressed in the next release.
