### ISSUE TITLE
enforce/optional check for canonical CBOR in response

### ISSUE THREAD

**Issue by nooobcoder** [fido-alliance/conformance-test-tools-resources#753]
Can check for response CBOR being canonically correct in the next release? If not enforce, can check be added to check for the same to do it optionally?

**Comment by nooobcoder** [comment]
Links to https://github.com/fido-alliance/conformance-test-tools-resources/issues/445

**Comment by iirachek** [comment]
Will see if it can be implemented in the next release, but it is low priority.

**Comment by iirachek** [comment]
Check for authenticator replies being a canonical CBOR got added in v1.7.21
