### ISSUE TITLE
CredProtect Test P-1: this.skip is not a function

### ISSUE THREAD

**Issue by wdxaseczq** [fido-alliance/conformance-test-tools-resources#754]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [X] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [X] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.7.19

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [X] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
When running the CredProtect test P-1, the error "this.skip is not a function" occurred.
According to the test description (the javascript code), this test should be skipped because our authenticator has returned "alwaysUv": true in GetInfo command response.
Below are getInfo.extensions and getInfo.options our authenticator returned:
`"extensions": ["credProtect", "hmac-secret"]`
`"options":{
"plat" : false,
"rk": true,
"uv": true,
"up": true,
"pinUvAuthToken": true,
"credMgmt": true,
"makeCredUvNotRqd": false,
"alwaysUv": true
}`

**Comment by iirachek** [comment]
Will be patched early next week.

**Comment by iirachek** [comment]
Should be fixed in the latest 1.7.19-1 build.

**Comment by wdxaseczq** [comment]
Thank you iirachek ! This issue has been fixed.
