### ISSUE TITLE
Test tool not ignoring unknown transports.

### ISSUE THREAD

**Issue by ve7jtb** [fido-alliance/conformance-test-tools-resources#758]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [x ] CTAP2.0
- [x ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v1.7.19-1

## What is the OS and the version are you running?

For desktop tools
- [x ] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
[Authr-Generic-1 Generic FIDO protocol tests]
Previous versions of the test tool ignored unknown transports in getInfo. 
Now it seems to have a static list.  

AssertionError: getInfo.transports contains value lightning NOT in defined in: [usb,nfc,ble,internal]: expected [ 'usb', 'nfc', 'ble', 'internal' ] to include 'lightning'
    at n.eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5627:24)

We did have lightning as a transport for a while.  Apple objected to differentiating between USB and lightning so it was eventually taken out of WebAuthn L2.  However the one security key that supports lightning advertises it in getInfo as some applications do look for it.   The hybrid transport will also be a problem for some authenticators.  I think it is wrong to error on unknown transports, but at least lightning and hybrid need to be added.

**Comment by ve7jtb** [comment]
This issue with the lightning transport will block the certification of the only lightning key.

**Comment by iirachek** [comment]
The v1.7.20 build with a fix for this is available for download.
