### ISSUE TITLE
UVM should not be included in Full Feature Profile

### ISSUE THREAD

**Issue by ve7jtb** [fido-alliance/conformance-test-tools-resources#759]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.7.19-1

## What is the OS and the version are you running?

For desktop tools
- [ x] OSX
- [ x] Windows
- [ x] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
The UVM extension is not supported by browsers and may be removed in Webauthn L3. 
Microsoft doesn't support this extension.  It can be tested for but should not be required for full feature.

**Comment by iirachek** [comment]
UVM requirement will be removed in v1.17.20. 
Link to the relevant [PR](https://github.com/fido-alliance/ctap2.1-conformance-module/pull/20).

**Comment by ve7jtb** [comment]
When will 1.17.20 be released?  This is holding up certification applications.

**Comment by pheimfido** [comment]
Plan to release early next week.

Thank you,

Paul



*Paul Heim *| Certification Director | FIDO Alliance

T: +1 623-200-3994

***@***.*** | www.fidoalliance.org

**Comment by iirachek** [comment]
@ve7jtb 
The v1.7.20 build with a fix for this is available for download.
