### ISSUE TITLE
1.17.20 error on all NFC tests

### ISSUE THREAD

**Issue by ve7jtb** [fido-alliance/conformance-test-tools-resources#762]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [ x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x ] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.17.20

## What is the OS and the version are you running?

For desktop tools
- [ x] OSX
- [ x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

NFC tests all broken.

They all fail with:
TypeError: Cannot read property 'transport' of undefined
    at getReaderDevice (/Applications/FIDO Alliance - Certification Conformance Testing Tools.app/Contents/Resources/app.asar/dependencies/transports/nfcdep.js:325:19)
    at Object.forceResetCard (/Applications/FIDO Alliance - Certification Conformance Testing Tools.app/Contents/Resources/app.asar/dependencies/transports/nfcdep.js:374:22)
    at Proxy.sendReset (eval at compileCode (js/sandbox.js:25:26), <anonymous>:2649:41)
    at resetForMakeCred (eval at compileCode (js/sandbox.js:25:26), <anonymous>:3451:12)
    at n.eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:6142:16)

It looks like it is doing getInfo then erroring 

[CTAP2.1] GetInfo: ---> Sending CTAP CMD... 04 undefined
/Applications/FIDO Alliance - Certification Conformance Testing Tools.app/Contents/Resources/app.asar/dependencies/transports/nfcdep.js:238 [NFC] ---> DATA SENT: 00a4040008a0000006472f000100
/Applications/FIDO Alliance - Certification Conformance Testing Tools.app/Contents/Resources/app.asar/dependencies/transports/nfcdep.js:243 [NFC] <--- DATA RECEIVED: 5532465f56329000
/Applications/FIDO Alliance - Certification Conformance Testing Tools.app/Contents/Resources/app.asar/dependencies/transports/nfcdep.js:211 [NFC] RECEIVED  SW_NO_ERROR
/Applications/FIDO Alliance - Certification Conformance Testing Tools.app/Contents/Resources/app.asar/dependencies/transports/nfcdep.js:238 [NFC] ---> DATA SENT: 80100000010400
/Applications/FIDO Alliance - Certification Conformance Testing Tools.app/Contents/Resources/app.asar/dependencies/transports/nfcdep.js:243 [NFC] <--- DATA RECEIVED: 00b10184665532465f5632684649444f5f325f306c4649444f5f325f315f505245684649444f5f325f3102856b6372656450726f746563746b686d61632d7365637265746c6c61726765426c6f624b65796863726564426c6f626c6d696e50696e4c656e6774680350a25342c03cdc44148e46f4807fca511c04ac62726bf5627570f564706c6174f468616c776179735576f468637265644d676d74f569617574686e72436667f569636c69656e7450696ef46a6c61726765426c6f6273f56e70696e557641757468546f6b656ef56f7365744d696e50494e4c656e677468f5706d616b654372656455764e6f74527164f57563726564656e7469616c4d676d617b
/Applications/FIDO Alliance - Certification Conformance Testing Tools.app/Contents/Resources/app.asar/dependencies/transports/nfcdep.js:211 [NFC] RECEIVED  undefined
/Applications/FIDO Alliance - Certification Conformance Testing Tools.app/Contents/Resources/app.asar/dependencies/transports/nfcdep.js:226 [NFC] Bytes remaining:  123
/Applications/FIDO Alliance - Certification Conformance Testing Tools.app/Contents/Resources/app.asar/dependencies/transports/nfcdep.js:238 [NFC] ---> DATA SENT: 80c000007b
/Applications/FIDO Alliance - Certification Conformance Testing Tools.app/Contents/Resources/app.asar/dependencies/transports/nfcdep.js:243 [NFC] <--- DATA RECEIVED: 7450726576696577f5051905000682020107080818800982636e6663637573620a83a263616c672664747970656a7075626c69632d6b6579a263616c672764747970656a7075626c69632d6b6579a263616c67382264747970656a7075626c69632d6b65790b1910000cf40d040e1a000507010f182010011418649000
/Applications/FIDO Alliance - Certification Conformance Testing Tools.app/Contents/Resources/app.asar/dependencies/transports/nfcdep.js:211 [NFC] RECEIVED  SW_NO_ERROR
VM225:3287 [CTAP2.1] GetInfo: <--- Received response {statusCode: 0, type: "GetInfo", cborResponse: {…}, cborResponseStruct: {…}, cborBuffer: Uint8Array(378), …}

**Comment by iirachek** [comment]
Reuploaded v1.7.20 with a fix
