### ISSUE TITLE
Check that metadata ROOTs BasicConstaints are set to FALSE

### ISSUE THREAD

**Issue by yackermann** [fido-alliance/conformance-test-tools-resources#764]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [x] CTAP2.0
- [x] CTAP2.1
- [x] UAF 1.1
- [x] U2F 1.1
- [x] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [x] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [x] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## Issue description

During the interop testing we found that if metadata root certificate BasicConstraint extension is marked as critical it is failing on majority of the servers.

I suggest adding test that checks that Root certificate BasicConstaint extension is set to FALSE.

**Comment by iirachek** [comment]
Fixed as part of v1.7.21

**Comment by geofli** [comment]
So, should it be the issue of server?
If BasicConstraint extension of ROOT certificate is marked as not critical, how about BasicConstraint in Intermediate certificate and attestation certificate? both should not be marked as critical?
If both ROOT and Intermediate are in metadata, for example, https://opotonniee.github.io/fido-mds-explorer/?aaguid=42b4fb4a-2866-43b2-9bf7-6c6669c2e5d3, is it true that only BasicConstraint in ROOT affects the result?

**Comment by iirachek** [comment]
> If BasicConstraint extension of ROOT certificate is marked as not critical, how about BasicConstraint in Intermediate certificate and attestation certificate? both should not be marked as critical?

Good question. In practice the answer will be: depends on the implementation.

To my knowledge, Basic Constraints isn't explicitly required to be **evaluated** or **understood** by any of the current FIDO specs, so the server can't be blamed. Whether this needs to be adjusted is a topic for discussion.

The above is based on an educated guess that the issue is in servers not understanding Basic Constraints extension. There may very well be an entirely different reason why the issue occurs.

**Comment by geofli** [comment]
I looked through Windows and macos trust Root list, all of the certificates have BasicConstaints set to TRUE.

**Comment by iirachek** [comment]
This check will likely be removed. Instead server conformance may get a new test for BasicConstraints support.
