### ISSUE TITLE
Authr-MakeCred-Resp-1 P-04 doesn't honor the hash algorithm

### ISSUE THREAD

**Issue by serianox** [fido-alliance/conformance-test-tools-resources#765]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [X] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [X] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?

1.7.20-4

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [X] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

In Authr-MakeCred-Resp-1 P-04, if the security key signs the attestation with a hash algorithm other than SHA-256 (e.g. SHA-384, SHA3-512), the verification fails.

In _verifySignature@dependencies/cryptodep.js:192_, the hash algorithm for the signature is hardcoded to SHA-256. The function doesn't use the _alg_ field to map the signature algorithm to the hash using _COSE_ALG_HASH_.

**Comment by iirachek** [comment]
Fixed as part of v1.7.21
