### ISSUE TITLE
CTAP1.2 General-1 P-1 Test using invalid short HID encoding

### ISSUE THREAD

**Issue by ve7jtb** [fido-alliance/conformance-test-tools-resources#768]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [ x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ x] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.7.20-3

## What is the OS and the version are you running?

For desktop tools
- [ x] OSX
- [ x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description

Tool sends 
[HID] DATA SENT: 156c8bf28300050003000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

This is using short encoding.  It works with Pre CTAP devices eg the Yubikey Neo will respond.
The original U2F specification had several encodings of commands that were supported including a non ISO compliant encoding.

In CTAP1.0 this led to a number of interop issues.   In CTAP1.1 we clarified that "all raw U2F messages are encoded using extended length APDU encoding."
https://fidoalliance.org/specs/fido-u2f-v1.1-id-20160915/fido-u2f-hid-protocol-v1.1-id-20160915.html#u2fhid-protocol-implementation

Both CTAP1.1 and 1.2 are clear that all U2F HID messages are encoded using extended length.  

In raw messages which is the transport-independent documentation of the commands that supports HID, NFC, and BLE both the long and the short ISO encodings are shown.   
https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-raw-message-formats-v1.2-ps-20170411.html#other-messages

So sending the short encoding over NFC is supported but sending it over HID is a violation of the HID transport spec.

It may work with some authenticators, but we don't know of any platforms that send short encoding over HID as that is a violation of the spec.

The conformance test needs to use long encoding for all HID tests. 

I appreciate that the tests use hand crafted binary messages so the message encoding is not obvious.

The older CTAP1.1 MDS2 tests must not have had this issue otherwise no CTAP2 Yubikey would have passed as we dropped support for short encoding over HID as part of supporting CTAP2. 

The problem may be that some of the general tests don't use transport-specific encoding, so are using the NFC encoding over HID.  

It also would not surprise me if other vendors are arguably violating the CTAP1.2 spec to pass the conformance tool.

**Comment by iirachek** [comment]
Fixed as part of 1.7.21
