### ISSUE TITLE
Self-conformance tool fails to parse Attestation Certificate with Basic Constraints value "30 03 01 01 00"

### ISSUE THREAD

**Issue by IwanTris** [fido-alliance/conformance-test-tools-resources#769]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [x] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [x] CTAP2.1
- [ ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [x] Security Key / FIDO2 / U2F authenticators
- [ ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.7.20-4

## What is the OS and the version are you running?

For desktop tools
- [ ] OSX
- [x] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
While running self-conformance tool v1.7.20-4 for **CTAP 2.1 - MDS3**, subgroup **MakeCredential Response** step **P-04**, we encountered the following error:
_Error: hExtV parse error: 3003010100
    at X509.getExtBasicConstraints (js/vendor/jsrsasign.min.js:238:4013)
    at Proxy.getCertificateInfoObject (js/utils.js:927:52)
    at n.eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:8159:32)_

The attestation certificate returned by the applet ([IPS_attestation_NFC_Test_1.zip](https://github.com/user-attachments/files/16962160/IPS_attestation_NFC_Test_1.zip)) has Basic Constraints value "30 03 01 01 00", which according to https://www.rfc-editor.org/rfc/rfc5280 means cA = FALSE.

30: SEQUENCE
03: length
     01: BOOLEAN
     01: length
     00: FALSE

   _BasicConstraints ::= SEQUENCE {
        cA                      BOOLEAN DEFAULT FALSE,
        pathLenConstraint       INTEGER (0..MAX) OPTIONAL }_

This cA value is the same as the expected value by self-conformance tool: _(6) Basic Constraints extension MUST have the CA component set to false_. 

However, it seems that the self-conformance tool fails to parse the Basic Constraints TLV. 
_Error: hExtV parse error: 3003010100
    at X509.getExtBasicConstraints (js/vendor/jsrsasign.min.js:238:4013)
    at Proxy.getCertificateInfoObject (js/utils.js:927:52)
    at n.eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:8159:32)_

For comparison, when the attestation certificate has the Basic Constraints value "30 00" (cA has defaut value FALSE), the self-conformance tool successfully parses the Basic Constraints TLV.

Can you please help to check why the self-conformance tool fails to parse the Attestation certificate with Basic Constraints "30 03 01 01 00"? 

Thank you

**Comment by iirachek** [comment]
The conformance tools use [jsrsasign](https://github.com/kjur/jsrsasign) for the processing of certificates, and the [function](https://github.com/kjur/jsrsasign/blob/58bb24192f501927014b67911bbde8ef27532319/src/x509-1.1.js#L788) for parsing basicConstraints extension is written in a way where explicitly defined `cA:FALSE` leads to an error.

With that said, on page 135 in [rfc5280](https://www.rfc-editor.org/rfc/rfc5280) the second paragraph states:
>    Implementers should note that the DER encoding of SET or SEQUENCE
>    components whose value is the DEFAULT omit the component from the
>    encoded certificate or CRL.  For example, a BasicConstraints
>    extension whose cA value is FALSE would omit the cA boolean from the
>    encoded certificate.

So even though other libraries may process such extension value, I believe the `cA:FALSE` should still be omitted, i.e. the correct value for basicConstraints would be `30 00`.

**Comment by IwanTris** [comment]
Hi iirachek,
Thank you for the answer.
