### ISSUE TITLE
Attestation root certificates for UAF MDS2 Server tests have expired in 2022

### ISSUE THREAD

**Issue by vs-nnl** [fido-alliance/conformance-test-tools-resources#770]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## FIRST PRE CHECK

- [X ] I SOLEMNLY SWEAR THAT I HAVE SEARCHED [DOCUMENTATION](https://github.com/fido-alliance/conformance-test-tools-resources/tree/master/docs) AND WAS NOT ABLE TO RESOLVE MY ISSUE

## What protocol are you implementing?

- [ ] FIDO2 Server
- [ ] CTAP2.0
- [ ] CTAP2.1
- [X ] UAF 1.1
- [ ] U2F 1.1
- [ ] U2F 1.2

NOTE: UAF 1.0 certification have been officially sunset. U2F 1.2 only supported version of U2F.

## What is your implementation class?

- [ ] Security Key / FIDO2 / U2F authenticators
- [X ] Server
- [ ] UAF Client-ASM-Authenticator combo
- [ ] UAF Client
- [ ] UAF ASM-Authenticator

If you are platform authenticator vendor, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
1.7.21-3

## What is the OS and the version are you running?
MacOS 14.6.1

For desktop tools
- [ X] OSX
- [ ] Windows
- [ ] Linux

For UAF mobile tools
- [ ] iOS
- [ ] Android

## Issue description
Attestation root certificates for UAF MDS2 Server tests have expired in 2022. A few are listed below:

FFFF#FC03 - expired on Feb 28, 2022
FFFF#FC06 - expired on March 3, 2022
FFFF#FC0B - expired on March 3, 2022

Due to this issue, UAF server conformance tests cannot be run.

**Comment by iirachek** [comment]
I've uploaded a new version v1.7.21.4 with renewed certificates.
