### ISSUE TITLE
EMSA Signatures verification issue

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-test-tools-resources#94]
Tool version 0.8.36

Seems like something ECDSA specific is used during assertion, not taking in account metadata. Passes on ECDSA devices and fails on RSA. 

```
Error: Uknown signature algorithm "ALG_SIGN_RSA_EMSA_PKCS1_SHA256_RAW"!
    at d (build/polyfills.js:3:3991)
    at FIDORSAPSSSignatureToRAW (assets/modules/fido-uaf-v1.1-conformance-module/js/verifyassertion.js:86:19)
    at Promise.resolve.then (assets/modules/fido-uaf-v1.1-conformance-module/js/verifyassertion.js:325:50)
    at t.invoke (build/polyfills.js:3:11562)
    at n.run (build/polyfills.js:3:6468)
    at build/polyfills.js:3:3767
    at t.invokeTask (build/polyfills.js:3:12256)
    at n.runTask (build/polyfills.js:3:7153)
    at a (build/polyfills.js:3:2312)
```

**Comment by herrjemand** [comment]
I will have a look at it @k-tono

**Comment by herrjemand** [comment]
@k-tono Can I have a copy of your assertion?

**Comment by k-tono** [comment]
Client response for this case is:

`[{"assertions":[{"assertion":"AT59AgM-cQELLgkANGU0ZSM0MDkyDi4HAAABAQgAAgEKLiAAbE52DkMTahcX2KORmkVe2f7Kv4GPKrnkvC8I_2-gq0kJLiAAggogx02r9hCd3gvggr6f0CPhOB_OgjsQ8mArveD1eFwNLggAIgAAACEAAAAMLgEB91hyMb5YGIWXWpDydmGcoYc43DEk9Lveo-qXksJFboJXXyBod4RNHueFzKRuByE9qq7QFrx-xtOJAsHHUpnbk4-o5s7if8WaHghmCZrGQcneepeueKWuuXiWlBEtIc9qUdPuEfgwQC8nPVVT8oPplYnwPtTms_A_9_bvSv1gDlq6F3o-IRXnDQo1XCgiVyK04zvI3jkKlnqO4jZmhD7mH5iDqTEn2Ymi2BABduwlg9UIJrMKw8PUC4fYO0Gmg0jDDlbvMAMDwHg3tC1T3lJh6JXH_tr1uPM3WV6jAuCU3YEUzE3snf_Nz_ytdvKSZQ6xcnGbFuUPYMkeA4z_v6Z90wMIPgQBBi4AAcPJMeWlR0ie_u3Vtk9xPSZQ66YCufZqZSMgWnK4Zp0bWtfCDft0rrMwBpnU3QzzFPbBlFR6zsQiWuot5FSJDqJQbp4HFNAteXbYlx7ibXwJDV1WScL4DWdvmGPOTpsI1K8bcCG3i-SM0_F4WEDhcKpAbFn9XlVd_pA_N_LpFPxW24iTRA_IOV_XhZgMhtK-CqwpTdOFwyO2HFkqd6QSpn1CsZ7mM3EIrZ11p_hXPWGRQHyHaC2A5R34A9gczlp9G-lZxSesiLpv6UtdE1sSlalHZt1UQxYW1rtFoWsMlgQzL7kuPCbNJ4659zoSgKcsfoudNnA015MIsViVzYgupCo","assertionScheme":"UAFV1TLV"}],"fcParams":"eyJhcHBJRCI6ImFuZHJvaWQ6YXBrLWtleS1oYXNoOlQ0bGxhZkFIeFlSa3FYblRqMVJ3NXhtT1NlVSIsImNoYWxsZW5nZSI6Ikg5aVc5eUE5YUFYRl9sZWxRb2lfRGhVazUxNEFkOFRxdjB6Q25DcUtEcG8iLCJjaGFubmVsQmluZGluZyI6e30sImZhY2V0SUQiOiJhbmRyb2lkOmFway1rZXktaGFzaDpUNGxsYWZBSHhZUmtxWG5UajFSdzV4bU9TZVUifQ","header":{"appID":"","op":"Reg","upv":{"major":1,"minor":1}}}]`

**Comment by herrjemand** [comment]
@k-tono Thanks for that. I will take a look into that

**Comment by herrjemand** [comment]
Blocked by limited support by cryptographic libraries
